// ETIA application notes — 62 application points across 10 industries.
// Rendered on the Application page (grid + detail modal).

export type App = {
  id: string;
  industry: string;
  subCategory: string;
  product: string;
  title: string;
  hot?: boolean;
  intro: string;
  challenge: string;
  solution: string;
  benefit: string;
  highlights: string[];
  recommended: string;
};

export const apps: App[] = [
  // ───────────── 1. MEDICAL DEVICE ASSEMBLY (11) ─────────────
  { id: "AN-MED-001", industry: "Medical Device Assembly", subCategory: "Cardiovascular", product: "S2000 Elite", title: "Balloon Catheter Tip Bonding", hot: true, intro: "Cardiovascular catheters require strong, repeatable bonds at balloon, hub, and marker interfaces. UV spot curing with closed-loop control is the industry standard for this critical bonding application.", challenge: "Achieving repeatable, uniform 360° curing of balloon catheter bond lines without inducing thermal stress on the balloon film.", solution: "OmniCure S2000 Elite with Closed-Loop Feedback (CLF) technology and a 4-leg High Power Fiber Light Guide or Cure Ring optical accessory.", benefit: "Strong and repeatable bonding of plastic parts with NIST-traceable dose control.", highlights: ["Closed-Loop Feedback maintains constant irradiance for repeatable bonds", "R2000 Radiometer calibrates output across all assembly lines, NIST-traceable", "Cure Ring provides 360° uniform curing power for radial bond geometries", "Multi-leg Light Guide ensures equal energy output from each leg"], recommended: "OmniCure S2000 Elite" },
  { id: "AN-MED-002", industry: "Medical Device Assembly", subCategory: "Needle & Syringe", product: "LX500 V2", title: "Hypodermic Needle & Cannula Assembly", hot: true, intro: "Over 40 billion needles are manufactured annually worldwide, the majority bonded with UV-curable adhesives on lines running 400–1,000 units/minute.", challenge: "Bonding dissimilar materials — stainless steel cannula to polypropylene hub — in under 1 second on ultra-high-speed automated lines.", solution: "OmniCure LX500 V2 multi-channel UV LED controller with 365/385 nm V3 Heads for simultaneous multi-station curing.", benefit: "Sub-second cure with >25N pull strength, supporting fully automated high-speed assembly without bottlenecks.", highlights: ["4-channel simultaneous cure for rotary indexing assembly stations", "Intelli-Lamp technology maintains ±5% optical stability across full shifts", "PLC trigger integration for seamless automation line synchronization", "365/385 nm wavelength options matched to medical adhesive photoinitiators"], recommended: "OmniCure LX500 V2" },
  { id: "AN-MED-003", industry: "Medical Device Assembly", subCategory: "Sensors & Wearables", product: "S2000 Elite", title: "Medical Sensor Encapsulation", intro: "Biosensor and wearable medical electronics require protective encapsulation that withstands body fluid and sterilization exposure without thermal damage to sensitive circuitry.", challenge: "Protecting miniaturized biosensor electronics from moisture and chemical exposure without damaging heat-sensitive components.", solution: "OmniCure S2000 Elite with selectable band-pass filters for low-heat, dose-controlled encapsulant cure.", benefit: "Tack-free protective encapsulation in seconds, enabling immediate downstream processing and packaging.", highlights: ["Selectable optical filters tailor wavelength to encapsulant chemistry", "Low-heat cure profile protects thermally sensitive sensor components", "WEB UI enables remote monitoring across multiple encapsulation stations"], recommended: "OmniCure S2000 Elite" },
  { id: "AN-MED-004", industry: "Medical Device Assembly", subCategory: "Endoscope", product: "LX500 V2", title: "Endoscope Objective Lens Bonding", intro: "Endoscope tip assemblies pack optical fiber bundles, lens systems, and steering mechanisms into a sub-10mm housing — UV spot curing enables precise bonding without disturbing adjacent optics.", challenge: "Bonding precision optical lens stacks inside confined endoscope tip assemblies without disturbing optical alignment.", solution: "OmniCure LX500 V2 with fiber light guide delivery for targeted, low-divergence UV exposure in micro-bond areas.", benefit: "Sub-micron alignment preserved through cure, ensuring consistent image quality across production lots.", highlights: ["Fiber light guide delivers focused UV to sub-millimeter bond points", "Fast shutter response locks optical alignment the instant cure triggers", "Low-heat LED output prevents thermal drift in precision lens stacks"], recommended: "OmniCure LX500 V2" },
  { id: "AN-MED-005", industry: "Medical Device Assembly", subCategory: "Drug Delivery", product: "LX500 V2", title: "Drug Delivery Device Assembly", intro: "Auto-injectors and inhalers are regulated as combination products, requiring full process validation and batch traceability for every UV-cured bonding step.", challenge: "Bonding auto-injector and inhaler components at high volume while meeting strict combination-product validation requirements.", solution: "OmniCure LX500 V2 with SD card exposure logging for full batch traceability per FDA 21 CFR Part 820.", benefit: "Validated, repeatable bonds with automatic dose documentation for combination product compliance.", highlights: ["SD card automatically logs every exposure event and fault in real time", "StepCure programmable multi-phase profiles for complex bond geometries", "Repeatable ±5% dose control supports FDA process validation submissions"], recommended: "OmniCure LX500 V2" },
  { id: "AN-MED-006", industry: "Medical Device Assembly", subCategory: "Surgical Instruments", product: "S2000 Elite", title: "Surgical Instrument Bonding", intro: "Reusable surgical instruments must withstand hundreds of sterilization cycles (autoclave, EtO) without bond degradation at handle and shaft interfaces.", challenge: "Bonding handle, shaft, and tip components on reusable and single-use surgical instruments requiring sterilization-resistant bonds.", solution: "OmniCure S2000 Elite delivering high-irradiance, deep-cure UV exposure for thick adhesive bond lines.", benefit: "Autoclave- and EtO-resistant bonds that withstand repeated sterilization cycles.", highlights: ["200W lamp with up to 30 W/cm² supports thick bond-line deep cure", "Field-interchangeable filters match cure profile to adhesive chemistry", "Closed-loop feedback ensures consistent cure depth across production runs"], recommended: "OmniCure S2000 Elite" },
  { id: "AN-MED-007", industry: "Medical Device Assembly", subCategory: "IVD Diagnostics", product: "AC Small (AC4 or AC5)", title: "PCR & Microfluidic Diagnostic Chip Sealing", intro: "Lateral flow and PCR diagnostic cartridges require sub-100 µm precision channel sealing at extremely high production volumes (millions/month).", challenge: "Sealing microfluidic channels on diagnostic cartridges with sub-100 µm precision at high-volume production rates.", solution: "OmniCure AC Small Series (AC4/AC5) air-cooled UV LED area curing for uniform channel sealing across the cartridge.", benefit: "Leak-free, optically clear seals enabling reliable PCR amplification and lateral flow performance.", highlights: ["Patented individual LED module output ensures uniform seal across the chip", "Compact, air-cooled design integrates easily into high-speed cartridge lines", "No chiller required — reduced footprint for cleanroom diagnostic manufacturing"], recommended: "OmniCure AC Small (AC4 or AC5)" },
  { id: "AN-MED-008", industry: "Medical Device Assembly", subCategory: "Orthopedics & Implants", product: "S2000 Elite", title: "Implantable Device Coating", hot: true, intro: "Orthopedic implants require precise UV maskants during plasma spray and PEEK coating operations to protect critical surfaces without compromising biocompatibility.", challenge: "Applying UV maskants and protective coatings to orthopedic implants without compromising biocompatible surface treatments.", solution: "OmniCure S2000 Elite with NIST-traceable R2000 Radiometer calibration for validated, repeatable masking dose.", benefit: "Precise, documented protection of critical implant surfaces during plasma spray or PEEK coating operations.", highlights: ["NIST-traceable calibration supports implant manufacturing quality documentation", "User-reconfigurable filters for different maskant chemistries", "Repeatable masking dose across high-mix implant production runs"], recommended: "OmniCure S2000 Elite" },
  { id: "AN-MED-009", industry: "Medical Device Assembly", subCategory: "Wound Care", product: "AC Large (AC7 or AC8)", title: "Wound Care Dressing Lamination", intro: "Multi-layer wound dressings (hydrocolloid, foam, adhesive border) are laminated at roll-to-roll speed using solvent-free UV-curable adhesives.", challenge: "Laminating multi-layer wound dressings at roll-to-roll production speeds without solvent residue affecting skin contact materials.", solution: "OmniCure AC Large Series (AC7/AC8) air-cooled large-area UV LED for continuous web lamination.", benefit: "High-speed, uniform lamination with no solvent residue — safe for direct skin contact materials.", highlights: ["Large-area curing widths (150–300mm) match dressing web widths", "Adjoinable heads scale to any production line width", "Solvent-free cure eliminates residue concerns for skin-contact materials"], recommended: "OmniCure AC Large (AC7 or AC8)" },
  { id: "AN-MED-010", industry: "Medical Device Assembly", subCategory: "IV & Fluid Delivery", product: "LX500 V2", title: "IV Line & Micro-Tube Assembly", intro: "IV administration sets and micro-tube connectors require particulate-free bonding meeting USP <788> standards for parenteral fluid delivery.", challenge: "Bonding micro-tube connectors and Y-sites on IV administration sets at high throughput with zero particulate contamination.", solution: "OmniCure LX500 V2 spot curing with precision light guides for clean-room compatible, solvent-free bonding.", benefit: "Particulate-free bonds meeting USP <788> requirements for parenteral fluid delivery systems.", highlights: ["Solvent-free, one-component adhesive cure eliminates particulate generation", "Precision light guides target micro-bond areas without overspill", "Cleanroom-compatible compact system footprint"], recommended: "OmniCure LX500 V2" },
  { id: "AN-MED-011", industry: "Medical Device Assembly", subCategory: "IVD Diagnostics", product: "AC Small (AC4/AC5)", title: "In-Vitro Diagnostics — Lateral Flow & Cartridge Assembly", intro: "Rapid diagnostic test cartridges are manufactured at extremely high unit volumes, requiring the lowest-cost, fastest UV cure cycle achievable.", challenge: "Bonding membrane layers and housing components on rapid test cartridges at extremely high unit volumes (millions/month).", solution: "OmniCure AC Small Series for fast, low-cost, high-throughput cartridge sealing and housing bonding.", benefit: "Sub-second cure enabling cost-effective, mass-volume diagnostic test manufacturing.", highlights: ["Compact AC4/AC5 footprint minimizes capital cost per assembly station", "Sub-second cure cycle matches highest-volume cartridge production rates", "Air-cooled — no chiller infrastructure required at scale"], recommended: "OmniCure AC Small (AC4/AC5)" },

  // ───────────── 2. AUTOMOTIVE & ADAS (8) ─────────────
  { id: "AN-AUT-001", industry: "Automotive & ADAS", subCategory: "EV Battery", product: "S2000 Elite", title: "EV Battery Tab & Cell Bonding", hot: true, intro: "Gigafactory-scale EV battery production requires UV curable materials that bond cell components without thermal damage to lithium-ion cells. See Case Study B1 for full market analysis.", challenge: "Bonding battery cell tabs and module components at gigafactory scale without inducing thermal stress on lithium-ion cells.", solution: "OmniCure S2000 Elite with Closed-Loop Feedback for consistent, low-heat dose delivery across high-volume lines.", benefit: "Zero-heat bonding preserving cell integrity while meeting gigafactory throughput targets (GWh-scale).", highlights: ["Closed-loop feedback ensures consistent dose across GWh-scale production", "Compatible with vibration-resistant adhesives (cell-to-weld protection)", "See Case Study B1 for full EV battery manufacturing economics"], recommended: "OmniCure S2000 Elite" },
  { id: "AN-AUT-002", industry: "Automotive & ADAS", subCategory: "ADAS & Sensors", product: "LX500 V2", title: "Automotive Sensor Potting", hot: true, intro: "Radar, ultrasonic, and inertial sensors for ADAS systems require potted protection meeting IATF 16949 traceability across the vehicle's 15-year service life.", challenge: "Potting radar, ultrasonic, and inertial sensors used in ADAS systems while meeting IATF 16949 traceability requirements.", solution: "OmniCure LX500 V2 with SD card data logging for full batch documentation of every potting cure cycle.", benefit: "Documented, repeatable potting that supports automotive PPAP submission and field-recall traceability.", highlights: ["Automatic SD card logging supports PPAP and IATF 16949 documentation", "365–405 nm wavelength options match automotive potting compound chemistries", "±5% optical stability ensures consistent potting across production volume"], recommended: "OmniCure LX500 V2" },
  { id: "AN-AUT-003", industry: "Automotive & ADAS", subCategory: "Connectors & Sealing", product: "LX500 V2", title: "Connector & Housing Sealing", intro: "Automotive electrical connectors require IP67/IP69K environmental sealing across high-mix, low-volume connector variants.", challenge: "Sealing electrical connector housings against moisture and dust ingress on high-mix automotive production lines.", solution: "OmniCure LX500 V2 spot curing for targeted, fast sealant cure on connector interfaces.", benefit: "Reliable environmental sealing achieved in seconds, supporting high-mix, low-volume connector variants.", highlights: ["Fast cure cycle accommodates high-mix, low-volume connector changeovers", "Targeted spot curing avoids unintended exposure of adjacent pins", "Foot pedal or PLC trigger options for flexible station integration"], recommended: "OmniCure LX500 V2" },
  { id: "AN-AUT-004", industry: "Automotive & ADAS", subCategory: "Camera Module", product: "S2000 Elite", title: "ADAS Camera Module Assembly", hot: true, intro: "ADAS camera modules must maintain ±10 µm optical alignment across –40°C to +105°C and 15G vibration for the vehicle's full service life.", challenge: "Bonding lens-to-barrel and barrel-to-sensor interfaces with automotive-grade alignment stability through extreme thermal and vibration environments.", solution: "OmniCure S2000 Elite with WEB UI remote monitoring across multiple ADAS camera assembly stations.", benefit: "Automotive-grade optical alignment stability through 15-year vehicle service life.", highlights: ["WEB UI enables remote monitoring of multiple assembly stations from one dashboard", "Closed-loop feedback ensures repeatable focus-lock cure dose", "IATF 16949-compatible traceability for automotive tier-1 qualification"], recommended: "OmniCure S2000 Elite" },
  { id: "AN-AUT-005", industry: "Automotive & ADAS", subCategory: "LiDAR & Autonomous Sensing", product: "LX500 V2 + AC Small", title: "LiDAR Sensor Assembly", intro: "Automotive LiDAR units contain 16–128 precisely aligned laser channels per unit, each requiring sub-micron alignment-preserving UV bonds.", challenge: "Bonding laser emitter, receiver lens, and MEMS scanning mirror assemblies at sub-micron alignment precision for autonomous vehicle LiDAR.", solution: "OmniCure LX500 V2 spot curing for emitter/receiver bonds combined with AC Small area curing for housing window sealing.", benefit: "Precision optical alignment maintained through automotive vibration and thermal cycling, ensuring ranging accuracy.", highlights: ["Sub-micron alignment preservation critical for ranging accuracy", "Combined spot + area curing covers both optical bonds and housing seals", "Validated for –40°C to +105°C automotive thermal environments"], recommended: "OmniCure LX500 V2 + AC Small" },
  { id: "AN-AUT-006", industry: "Automotive & ADAS", subCategory: "Headlamp", product: "AC Large (AC7)", title: "Headlamp Lens Bonding", intro: "Automotive headlamps must maintain sealing integrity across the vehicle lifetime despite extreme thermal cycling and UV-A exposure from sunlight.", challenge: "Bonding headlamp lens-to-housing interfaces that must withstand –40°C to +120°C thermal cycling and UV-A exposure.", solution: "OmniCure AC Large (AC7) large-area UV LED curing for full-perimeter lens bond line cure.", benefit: "Weather-resistant, optically clear bonds that maintain headlamp sealing integrity for vehicle lifetime.", highlights: ["Large-area exposure covers full lens perimeter bond line in one pass", "High peak irradiance (>5 W/cm²) supports fast-cycle production", "Adjoinable AC7 heads scale to any headlamp size or shape"], recommended: "OmniCure AC Large (AC7)" },
  { id: "AN-AUT-007", industry: "Automotive & ADAS", subCategory: "Automotive Electronics", product: "AC Small (AC5) or AC Large (AC7)", title: "PCB Conformal Coating — Automotive Electronics", intro: "ECU and powertrain control PCBs require IPC-CC-830-compliant protective coatings against under-hood moisture, fuel vapor, and thermal extremes.", challenge: "Protecting ECU and powertrain control PCBs from under-hood environmental exposure at IATF 16949 quality levels.", solution: "OmniCure AC Small or AC Large Series for inline conformal coating cure on automotive PCB assembly conveyors.", benefit: "5–10 second cure cycle integrated into existing SMT lines with full automotive batch traceability.", highlights: ["Inline integration with existing SMT/SMD conveyor lines", "5–10 second cure eliminates thermal oven cure bottleneck", "IATF 16949-aligned process documentation support"], recommended: "OmniCure AC Small (AC5) or AC Large (AC7)" },
  { id: "AN-AUT-008", industry: "Automotive & ADAS", subCategory: "Interior Trim", product: "AC Large (AC8-HD)", title: "Dashboard & Interior Trim Panel Coating", intro: "Dashboard and trim panels require scratch-resistant, anti-fingerprint finishes cured at high line speed without cabin VOC emissions.", challenge: "Applying scratch-resistant, anti-fingerprint coatings to dashboard and trim panels at high line speeds without VOC emissions.", solution: "OmniCure AC Large (AC8-HD) high-dose UV LED curing for fast, complete cure of decorative/protective coatings.", benefit: "High-gloss, durable surface finish cured in seconds with zero solvent emissions in the cabin environment.", highlights: ["High-dose AC8-HD delivers >15 W/cm² for complete single-pass cure", "Zero VOC emissions support cabin air quality standards", "Durable finish withstands daily wear and UV exposure through windshield"], recommended: "OmniCure AC Large (AC8-HD)" },

  // ───────────── 3. ELECTRONICS & PCB ASSEMBLY (9) ─────────────
  { id: "AN-ELC-001", industry: "Electronics & PCB Assembly", subCategory: "PCB Assembly", product: "AC Small (AC4/AC5) or AC Large (AC7)", title: "PCB Conformal Coating", hot: true, intro: "UV-curable conformal coatings cure tack-free in 3–10 seconds, transforming coating from a production bottleneck into a negligible process step.", challenge: "Protecting PCBs from moisture, dust, and chemical exposure while maintaining inline production speed without a thermal cure bottleneck.", solution: "OmniCure AC Small or AC Large Series for selective or full-board UV LED conformal coating cure.", benefit: "3–10 second cure replacing 20–60 minute thermal cure ovens, eliminating the coating step as a line bottleneck.", highlights: ["3–10 second cure vs. 20–60 minute thermal oven cure", "Selective masking-free area curing for connector/test-point exclusion zones", "Immediate fluorescent inspection confirms complete coating coverage"], recommended: "OmniCure AC Small (AC4/AC5) or AC Large (AC7)" },
  { id: "AN-ELC-002", industry: "Electronics & PCB Assembly", subCategory: "Display Bonding", product: "LX500 V2", title: "Display Module Assembly (Optically Clear Adhesive)", hot: true, intro: "Display module OCA bonding requires zero optical haze and uniform bond line thickness for consumer electronics quality standards.", challenge: "Bonding display panels to cover glass or touch sensors with zero optical haze and uniform bond line thickness.", solution: "OmniCure LX500 V2 with V3 LED Heads delivering uniform, low-divergence exposure for OCA bonding.", benefit: "Optically clear, bubble-free bonds meeting consumer electronics display quality standards.", highlights: ["V3 LED Heads deliver uniform beam profile minimizing edge effects", "365–405 nm wavelength options match OCA photoinitiator absorption", "Multi-channel control for simultaneous multi-zone display bonding"], recommended: "OmniCure LX500 V2" },
  { id: "AN-ELC-003", industry: "Electronics & PCB Assembly", subCategory: "Wire & Coil", product: "LX500 V2 (365 nm)", title: "Wire Tacking & Strain Relief", intro: "Wire bundles and coil windings need vibration-resistant strain relief applied without adding bulk or extended cure time.", challenge: "Securing wire bundles and coil windings against vibration-induced fatigue without adding bulk or heat-curing time.", solution: "OmniCure LX500 V2 at 365 nm for fast tacking of UV-curable wire coating adhesives.", benefit: "Instant strain relief cure enabling immediate handling and downstream assembly.", highlights: ["Instant tack cure enables immediate downstream handling", "365 nm matched to standard wire-coating adhesive chemistries", "Compact head design fits tight coil-winding work envelopes"], recommended: "OmniCure LX500 V2 (365 nm)" },
  { id: "AN-ELC-004", industry: "Electronics & PCB Assembly", subCategory: "SMT Assembly", product: "LX500 V2", title: "SMT Component Bonding (Adhesive Dot)", intro: "Surface-mount components require tacking before reflow soldering on high-speed pick-and-place lines running thousands of placements/hour.", challenge: "Tacking surface-mount components in place before reflow soldering on high-speed pick-and-place lines.", solution: "OmniCure LX500 V2 spot curing synchronized with pick-and-place cycle times.", benefit: "Sub-second tack cure preventing component shift during reflow, improving first-pass yield.", highlights: ["Sub-second cure synchronized to pick-and-place takt time", "Prevents component shift during reflow, improving first-pass yield", "PLC-synchronized triggering for seamless SMT line integration"], recommended: "OmniCure LX500 V2" },
  { id: "AN-ELC-005", industry: "Electronics & PCB Assembly", subCategory: "Semiconductor Assembly", product: "LX500 V2 or S2000 Elite", title: "Flip-Chip & BGA Underfill Cure", intro: "Underfill between flip-chip/BGA die and substrate must cure without thermal warpage on increasingly fine-pitch interconnects.", challenge: "Curing underfill material between flip-chip or BGA die and substrate without thermal warpage on fine-pitch interconnects.", solution: "OmniCure LX500 V2 or S2000 Elite delivering controlled, low-heat UV-initiated underfill cure.", benefit: "Warpage-free cure preserving interconnect integrity on high-density fine-pitch packages.", highlights: ["Low-heat UV cure prevents differential thermal expansion warpage", "Compatible with fine-pitch micro-bump and ball-grid interconnects", "Controlled dose preserves underfill flow-fill characteristics before gel"], recommended: "OmniCure LX500 V2 or S2000 Elite" },
  { id: "AN-ELC-006", industry: "Electronics & PCB Assembly", subCategory: "Semiconductor Packaging", product: "S2000 Elite", title: "Semiconductor Package Glob-Top Encapsulation", intro: "Glob-top encapsulation protects wire-bonded die, requiring precise dose control to avoid mechanical stress on fine gold bond wires.", challenge: "Encapsulating wire-bonded die with UV-curable glob-top material at controlled dose to avoid bond wire damage.", solution: "OmniCure S2000 Elite with Closed-Loop Feedback for precise, repeatable encapsulant dose control.", benefit: "Reliable wire bond protection with consistent encapsulant coverage across production lots.", highlights: ["Closed-loop dose control protects delicate gold bond wires from cure stress", "Repeatable coverage critical for moisture and mechanical protection", "Compatible with high-viscosity glob-top formulations"], recommended: "OmniCure S2000 Elite" },
  { id: "AN-ELC-007", industry: "Electronics & PCB Assembly", subCategory: "OLED Display", product: "LX500 V2 (365 nm)", title: "OLED Panel Encapsulation", intro: "OLED stacks are extremely moisture-sensitive and cannot tolerate the heat of conventional thermal edge-seal cure.", challenge: "Encapsulating moisture-sensitive OLED stacks with UV-curable barrier adhesive without thermal damage to organic layers.", solution: "OmniCure LX500 V2 at 365 nm for low-heat, fast-cure edge sealant application.", benefit: "Hermetic-equivalent edge sealing achieved without exposing OLED materials to damaging heat.", highlights: ["Low-heat 365 nm LED cure protects moisture-sensitive organic layers", "Fast cure cycle compatible with high-volume display production", "Edge-seal barrier performance approaches hermetic glass-frit sealing"], recommended: "OmniCure LX500 V2 (365 nm)" },
  { id: "AN-ELC-008", industry: "Electronics & PCB Assembly", subCategory: "Wearable Electronics", product: "LX500 V2 (compact)", title: "Wearable Device PCB Potting", intro: "Wearable device PCBs require flexible, low-stress potting in space-constrained housings without adding bulk to thin form factors.", challenge: "Potting miniaturized PCBs in wearable devices with flexible, low-stress UV-curable compounds in space-constrained housings.", solution: "OmniCure LX500 V2 compact configuration for targeted potting cure in small-footprint assemblies.", benefit: "Flexible, low-stress potting protection without adding bulk to thin wearable form factors.", highlights: ["Compact head footprint fits small wearable assembly fixtures", "Low-stress cure profile compatible with flexible potting compounds", "Fast cure supports high-volume consumer wearable production"], recommended: "OmniCure LX500 V2 (compact)" },
  { id: "AN-ELC-009", industry: "Electronics & PCB Assembly", subCategory: "EV Charging", product: "AC Small (AC5)", title: "EV Charger & Power Electronics Board Coating", intro: "EV charging station power electronics boards face outdoor humidity and thermal cycling exposure requiring robust conformal protection.", challenge: "Conformal coating of EV charging station power electronics boards exposed to outdoor humidity and thermal cycling.", solution: "OmniCure AC Small (AC5) for fast, uniform protective coating cure on power electronics assemblies.", benefit: "Weather-resistant board protection supporting EV charging infrastructure reliability and warranty targets.", highlights: ["Fast, uniform cure for outdoor-rated power electronics protection", "Compact AC5 footprint suits power board assembly cell layouts", "Supports EV charging infrastructure warranty and reliability targets"], recommended: "OmniCure AC Small (AC5)" },

  // ───────────── 4. PHOTONICS & ADVANCED PACKAGING (8) ─────────────
  { id: "AN-PHO-001", industry: "Photonics & Advanced Packaging", subCategory: "400G/800G/1.6T Transceivers", product: "LX500 V2 or S2000 Elite", title: "Optical Transceiver Module Assembly", hot: true, intro: "As optical transceiver data rates climb from 400G to 1.6T, alignment tolerances are tightening from ±500 nm to ±200 nm, demanding more stable UV dose control.", challenge: "Bonding laser-to-fiber and photodiode-to-lens interfaces at ±200 nm alignment tolerance as data rates climb to 1.6T.", solution: "OmniCure S2000 Elite (Closed-Loop Feedback) or LX500 V2 multi-channel spot curing for sub-100 nm-stable fiber pigtail bonding.", benefit: "Stable optical alignment maintained through 5+ years of continuous data center operation at next-generation data rates.", highlights: ["CLF technology maintains ±5% output stability across millions of bond cycles", "Sub-100 nm cure-shrinkage control critical at 1.6T alignment tolerances", "See Case Study B2 for full optical transceiver manufacturing analysis"], recommended: "OmniCure LX500 V2 or S2000 Elite" },
  { id: "AN-PHO-002", industry: "Photonics & Advanced Packaging", subCategory: "AI Data Center Switches", product: "LX500 V2", title: "Co-Packaged Optics (CPO) Fiber Array Bonding", hot: true, intro: "CPO integrates optical transceivers directly onto the same package substrate as the switch ASIC — one of the fastest-growing photonics packaging markets.", challenge: "Bonding fiber array units to silicon photonic engines co-packaged with switch ASICs at sub-100 nm alignment stability through UV cure shrinkage.", solution: "OmniCure LX500 V2 with V3 365 nm Heads and LS200 Radiometry for in-process dose verification at each bond site.", benefit: "Sub-100 nm post-cure alignment shift — meeting the precision threshold required for next-generation CPO switch platforms.", highlights: ["LS200 Radiometry provides in-process dose verification per bond site", "Sub-100 nm alignment stability meets CPO switch platform requirements", "See Case Study B3 for the CPO market opportunity and technical requirements"], recommended: "OmniCure LX500 V2" },
  { id: "AN-PHO-003", industry: "Photonics & Advanced Packaging", subCategory: "Silicon Photonics", product: "LX500 V2 + LS200", title: "Photonic Integrated Circuit (PIC) Packaging", hot: true, intro: "PIC packaging requires bonding 32–512 channel fiber array units (FAUs) to photonic chip edge couplers with index-matched UV epoxy at sub-micron precision.", challenge: "Bonding fiber array units to photonic chip edge couplers with index-matched UV epoxy at sub-micron precision.", solution: "OmniCure LX500 V2 multi-channel UV LED curing combined with LS200 in-situ dose measurement for process validation.", benefit: "Repeatable, low-shrinkage cure preserving fiber-to-waveguide coupling efficiency across high-volume PIC production.", highlights: ["Multi-channel LX500 V2 cures multiple FAU bond points simultaneously", "LS200 in-situ measurement supports process qualification documentation", "See Case Study B4 for PIC packaging market drivers and AI infrastructure context"], recommended: "OmniCure LX500 V2 + LS200" },
  { id: "AN-PHO-004", industry: "Photonics & Advanced Packaging", subCategory: "Foundry & OSAT", product: "S2000 Elite", title: "Silicon Photonics Wafer-Level Packaging", intro: "2.5D heterogeneous integration of silicon photonic wafers requires bonding interposers and waveguide structures without disturbing fine optical alignment.", challenge: "Bonding interposers and waveguide structures on silicon photonic wafers during 2.5D heterogeneous integration without disturbing fine alignment.", solution: "OmniCure S2000 Elite with NIST-traceable R2000 Radiometer for validated, repeatable wafer-level bonding dose.", benefit: "Process-qualified bonding compatible with foundry and OSAT (outsourced assembly and test) quality systems.", highlights: ["NIST-traceable calibration supports foundry/OSAT quality system requirements", "Repeatable wafer-level dose control across full 200–300 mm wafer diameters", "Compatible with 2.5D heterogeneous integration process flows"], recommended: "OmniCure S2000 Elite" },
  { id: "AN-PHO-005", industry: "Photonics & Advanced Packaging", subCategory: "Chiplet/CoWoS/UCIe", product: "LX500 V2 or AC Small", title: "Advanced Semiconductor Packaging — Chiplet & 2.5D/3D Integration", intro: "Chiplet-based architectures (UCIe, CoWoS) require UV bonding of chiplets to interposers and underfill cure on dense micro-bump arrays without thermal warpage.", challenge: "Bonding chiplets to interposers and curing underfill on dense micro-bump arrays without thermal warpage.", solution: "OmniCure LX500 V2 spot curing or AC Small area curing for low-heat, dose-controlled chiplet bonding and underfill cure.", benefit: "Warpage-free die attach supporting next-generation AI accelerator and HBM memory packaging architectures.", highlights: ["Low-heat cure prevents warpage on dense micro-bump interconnects", "Compatible with HBM memory stack and AI accelerator packaging flows", "See Case Study B5 for advanced packaging market and process requirements"], recommended: "OmniCure LX500 V2 or AC Small" },
  { id: "AN-PHO-006", industry: "Photonics & Advanced Packaging", subCategory: "Wafer Dicing", product: "AC Large (AC7/AC8)", title: "UV Dicing Tape Release for Wafer Singulation", intro: "Ultra-thin wafers (50–100 µm) used in 3D stacking require clean UV dicing tape release without die breakage across full 200–450 mm wafer diameters.", challenge: "Releasing ultra-thin diced wafers from UV dicing tape cleanly for die pickup without breakage.", solution: "OmniCure AC Large Series (AC7/AC8) for uniform, full-wafer UV exposure with precise de-tacking dose control.", benefit: "Clean die release with zero contamination — critical for thin-die 3D stacking and chiplet manufacturing yield.", highlights: ["Uniform full-wafer exposure across 200–450 mm wafer diameters", "Precise de-tacking dose avoids over-exposure of adjacent film layers", "<30 second cycle time matches semiconductor fab throughput requirements"], recommended: "OmniCure AC Large (AC7/AC8)" },
  { id: "AN-PHO-007", industry: "Photonics & Advanced Packaging", subCategory: "Emerging Photonics", product: "LX500 V2", title: "LiDAR & Quantum Photonic Component Assembly", intro: "LiDAR and emerging quantum photonic systems require sub-micron pointing stability and, for quantum applications, low-outgassing optical adhesives.", challenge: "Bonding fiber and lens assemblies requiring sub-micron pointing stability and low-outgassing material compatibility.", solution: "OmniCure LX500 V2 precision spot curing with selectable wavelengths for cryogenic-compatible and standard optical adhesive systems.", benefit: "Precision optical bonding supporting both automotive LiDAR scale-up and emerging quantum photonic hardware development.", highlights: ["Selectable wavelengths support both standard and cryogenic-compatible adhesives", "Sub-micron pointing stability for laser delivery and fiber assemblies", "Applicable to early-stage quantum hardware development programs"], recommended: "OmniCure LX500 V2" },
  { id: "AN-PHO-008", industry: "Photonics & Advanced Packaging", subCategory: "High-Density Fiber Interconnect", product: "S2000 Elite or LX500 V2", title: "Active Optical Cable (AOC) & MT Ferrule Termination", intro: "AI server rack interconnects require high-density fiber ribbon cable termination in MT/MPO ferrule connectors at production-line speed.", challenge: "Terminating high-density fiber ribbon cables in MT/MPO ferrule connectors for AI server rack interconnects.", solution: "OmniCure S2000 Elite or LX500 V2 with multi-leg light guides for uniform multi-fiber ferrule bond cure.", benefit: "Consistent, low-loss ferrule termination supporting high-density AI cluster interconnect manufacturing volumes.", highlights: ["Multi-leg light guides cure entire multi-fiber ferrule array uniformly", "Low-loss termination critical for AI cluster interconnect bandwidth", "Scalable to high-volume AI data center infrastructure build-out"], recommended: "OmniCure S2000 Elite or LX500 V2" },

  // ───────────── 5. OPTICAL FIBER & CABLE MANUFACTURING (6) ─────────────
  { id: "AN-CAB-001", industry: "Optical Fiber & Cable Manufacturing", subCategory: "Fiber Connector", product: "S2000 Elite or LX500 V2", title: "Fiber Optic Connector Termination", hot: true, intro: "LC/SC/FC connector termination requires consistent epoxy cure across high-volume, multi-station connector assembly lines.", challenge: "Terminating single fiber connectors with consistent epoxy cure across high-volume, multi-station connector assembly lines.", solution: "OmniCure S2000 Elite or LX500 V2 with fiber light guide delivery for uniform connector ferrule bond cure.", benefit: "Low-loss, repeatable connector termination supporting telecom and data center fiber deployment volumes.", highlights: ["Fiber light guide delivery for uniform single-fiber ferrule cure", "Repeatable process supports telecom-scale deployment volumes", "Compatible with standard epoxy and UV-curable connector adhesives"], recommended: "OmniCure S2000 Elite or LX500 V2" },
  { id: "AN-CAB-002", industry: "Optical Fiber & Cable Manufacturing", subCategory: "Fiber Ribbon", product: "AC922S-F", title: "Fiber Ribbon Coating", intro: "Multi-fiber ribbon assemblies require UV-curable matrix coating at continuous production line speed without fiber damage.", challenge: "Coating multi-fiber ribbon assemblies with UV-curable matrix material at continuous production line speed without fiber damage.", solution: "OmniCure AC922S-F fiber-optimized UV LED curing system with custom optics for focused ribbon coating cure.", benefit: "High-speed, uniform ribbon matrix cure supporting high-density fiber ribbon cable manufacturing.", highlights: ["Custom fiber-optimized optics focus UV energy precisely onto the ribbon", "High-speed cure matches continuous ribbon production line rates", "Supports growing AI data center high-density fiber ribbon demand"], recommended: "OmniCure AC922S-F" },
  { id: "AN-CAB-003", industry: "Optical Fiber & Cable Manufacturing", subCategory: "Fiber Drawing", product: "AC Large UV LED (Fiber Draw Tower)", title: "Optical Fiber Draw Tower Primary & Secondary Coating", hot: true, intro: "Dual acrylate coatings on bare glass fiber must cure completely at draw speeds up to 3,000+ m/min without coating delamination.", challenge: "Curing dual acrylate coatings on bare glass fiber at draw speeds up to 3,000+ m/min without coating delamination.", solution: "OmniCure AC Large UV LED fiber draw tower system with 360° uniform exposure for high-speed primary/secondary coating cure.", benefit: "Complete, uniform coating cure at maximum draw speed, supporting capacity expansion for 5G and AI data center fiber demand.", highlights: ["360° uniform exposure ensures complete circumferential coating cure", "Supports draw speeds exceeding 3,000 m/min for continuous production", "Critical capacity-driver for 5G and AI data center fiber demand growth"], recommended: "OmniCure AC Large UV LED (Fiber Draw Tower)" },
  { id: "AN-CAB-004", industry: "Optical Fiber & Cable Manufacturing", subCategory: "Cable Jacket", product: "AC Large (AC8) with 360° Reflector", title: "Cable Jacket Cure", intro: "Finished cable assemblies require full-circumference UV jacket cure on continuous extrusion lines without rotation.", challenge: "Curing UV-curable cable jacket material around the full circumference of finished cable assemblies on continuous extrusion lines.", solution: "OmniCure AC Large (AC8) with 360° reflector assembly for full-circumference jacket cure.", benefit: "Uniform, full-coverage jacket cure on a single pass, eliminating the need for jacket rotation.", highlights: ["360° reflector eliminates need for cable rotation during cure", "Single-pass full coverage matches continuous extrusion line speed", "High-dose AC8 platform suitable for thick jacket wall sections"], recommended: "OmniCure AC Large (AC8) with 360° Reflector" },
  { id: "AN-CAB-005", industry: "Optical Fiber & Cable Manufacturing", subCategory: "Fiber Splice", product: "S2000 Elite or LX500 V2", title: "Fiber Splice Protection", intro: "Field and factory fiber splicing requires fast cure of splice protection sleeves and recoating of bare fiber at the splice point.", challenge: "Curing UV-curable splice protection sleeves and recoating bare fiber at splice points in field and factory operations.", solution: "OmniCure S2000 Elite or LX500 V2 portable spot curing for fast, field-compatible splice protection cure.", benefit: "Restored coating integrity and mechanical protection at splice points in seconds.", highlights: ["Portable spot curing configuration suitable for field splicing operations", "Seconds-fast cure minimizes splice-point exposure time", "Restores full mechanical protection equivalent to original fiber coating"], recommended: "OmniCure S2000 Elite or LX500 V2" },
  { id: "AN-CAB-006", industry: "Optical Fiber & Cable Manufacturing", subCategory: "Fiber Coating", product: "AC Large with 360° Reflector Array", title: "Tight-Buffer Fiber Coating", intro: "Indoor/outdoor cable constructions require tight-buffer coating applied to individual fibers with consistent wall thickness at line speed.", challenge: "Applying tight-buffer coating to individual fibers at continuous line speed with uniform wall thickness.", solution: "OmniCure AC Large Series with 360° reflector array for uniform tight-buffer coating cure around the fiber.", benefit: "Consistent buffer wall thickness and adhesion supporting reliable tight-buffer cable performance.", highlights: ["360° reflector array ensures uniform wall thickness around the fiber", "Consistent adhesion supports long-term tight-buffer cable reliability", "Matches continuous tight-buffer extrusion/coating line speeds"], recommended: "OmniCure AC Large with 360° Reflector Array" },

  // ───────────── 6. OPTICS & IMAGING SYSTEMS (3) ─────────────
  { id: "AN-OPT-001", industry: "Optics & Imaging Systems", subCategory: "Lens Assembly", product: "LX500 V2 (365 nm)", title: "Camera Lens Element Bonding", hot: true, intro: "Camera and imaging module manufacturing requires sub-micron centration accuracy for lens elements, locked permanently at the moment of UV cure.", challenge: "Bonding precision lens elements and lens-to-barrel interfaces with sub-micron centration accuracy.", solution: "OmniCure LX500 V2 at 365 nm with fast shutter response for instant alignment lock-in after active alignment.", benefit: "Optical alignment locked permanently at the moment of cure, preserving imaging performance across production volume.", highlights: ["Fast shutter response (~30 ms) locks alignment the instant cure triggers", "365 nm wavelength matched to standard optical cement photoinitiators", "Compatible with active-alignment fixtures for high-precision assembly"], recommended: "OmniCure LX500 V2 (365 nm)" },
  { id: "AN-OPT-002", industry: "Optics & Imaging Systems", subCategory: "Optical Assembly", product: "LX500 V2 + Large-Area Adaptor", title: "Prism & Beamsplitter Assembly", intro: "Cemented prism and beamsplitter assemblies (doublets/triplets) require controlled cure to avoid optical path distortion across larger bond areas.", challenge: "Bonding cemented prism and beamsplitter assemblies with controlled cure to avoid optical path distortion.", solution: "OmniCure LX500 V2 with large-area adaptor for uniform exposure across larger optical cement bond lines.", benefit: "Distortion-free optical cement cure with consistent refractive index across the bonded interface.", highlights: ["Large-area adaptor extends uniform exposure to larger cemented assemblies", "Consistent refractive index cure avoids optical path distortion", "Suitable for doublet/triplet lens cementing operations"], recommended: "OmniCure LX500 V2 + Large-Area Adaptor" },
  { id: "AN-OPT-003", industry: "Optics & Imaging Systems", subCategory: "AR Coating", product: "LX500 V2 (365 nm)", title: "AR Coating Bond / Protective Overlay", intro: "UV-curable anti-reflective coatings and protective overlays must cure without introducing coating stress or haze on precision optical surfaces.", challenge: "Curing UV-curable anti-reflective coatings and protective overlays without introducing coating stress or haze.", solution: "OmniCure LX500 V2 at 365 nm for fast, low-stress coating cure on precision optical surfaces.", benefit: "Haze-free, durable AR coating cure supporting high-transmission optical component manufacturing.", highlights: ["Low-stress cure profile avoids haze formation on precision optics", "Fast cure cycle supports high-throughput optical coating lines", "Compatible with multi-layer AR coating stack curing requirements"], recommended: "OmniCure LX500 V2 (365 nm)" },

  // ───────────── 7. PRINTING & GRAPHIC ARTS (3) ─────────────
  { id: "AN-PRT-001", industry: "Printing & Graphic Arts", subCategory: "Industrial Inkjet", product: "LX500 V2 Inline or AC Large LED", title: "UV Inkjet — Industrial & Wide-Format Printing", intro: "UV inkjet ink must cure instantly on non-absorbing substrates (plastic, metal, glass) at press speed without dot spread or smearing.", challenge: "Curing UV inkjet ink instantly on non-absorbing substrates at press speeds without dot spread or smearing.", solution: "OmniCure LX500 V2 inline configuration or AC Large LED for pinning and full-cure stages of the inkjet process.", benefit: "Instant, complete cure enabling printing on any substrate with zero drying time and no solvent emissions.", highlights: ["Pinning stage freezes dot position before spreading, preserving sharpness", "Full-cure stage completes mechanical/chemical resistance after all colors", "Zero drying time enables immediate finishing of printed substrates"], recommended: "OmniCure LX500 V2 Inline or AC Large LED" },
  { id: "AN-PRT-002", industry: "Printing & Graphic Arts", subCategory: "Flexo & Offset", product: "AC Large (AC8-HD) or NobleLight Mercury Arc", title: "Flexographic & Sheet-Fed Offset UV Printing", intro: "Flexo and offset presses are transitioning from mercury arc to UV LED for faster cure, lower energy, and reduced lamp maintenance.", challenge: "Curing UV flexo and offset inks at high press speeds while transitioning to more efficient, longer-life UV sources.", solution: "OmniCure AC Large (AC8-HD) high-dose UV LED, or NobleLight mercury arc systems for legacy press compatibility.", benefit: "Faster cure, lower energy consumption, and reduced lamp maintenance compared to conventional mercury arc systems.", highlights: ["AC8-HD high-dose output matches or exceeds mercury arc cure speed", "Instant on/off between print jobs reduces standby energy consumption", "NobleLight mercury arc option supports legacy press retrofit needs"], recommended: "OmniCure AC Large (AC8-HD) or NobleLight Mercury Arc" },
  { id: "AN-PRT-003", industry: "Printing & Graphic Arts", subCategory: "Container Decoration", product: "AC Small (AC2/AC4)", title: "Digital Label & Container Decoration", intro: "Cylindrical container and label decoration lines require compact, full-wrap UV cure modules that integrate easily into existing equipment.", challenge: "Curing UV ink and coatings on cylindrical containers and labels at high-speed decoration line rates with full-wrap coverage.", solution: "OmniCure AC Small Series (AC2/AC4) compact UV LED for label and container decoration line integration.", benefit: "Compact, energy-efficient cure module integrating easily into existing label and container decoration lines.", highlights: ["Compact footprint retrofits easily into existing decoration lines", "Energy-efficient operation reduces total line operating cost", "Full-wrap coverage suitable for cylindrical container geometries"], recommended: "OmniCure AC Small (AC2/AC4)" },

  // ───────────── 8. WOOD & FURNITURE COATINGS (6) ─────────────
  { id: "AN-WOD-001", industry: "Wood & Furniture Coatings", subCategory: "Flat Panel", product: "AC Large (AC8-HD) or NobleLight Mercury Arc", title: "UV Lacquer Cure — Flat Panel Furniture", hot: true, intro: "Flat furniture panel coating lines require consistent gloss and hardness at high conveyor speeds, with growing demand for energy-efficient LED alternatives to mercury arc.", challenge: "Curing UV lacquer topcoats on flat furniture panels at high conveyor speeds while achieving consistent gloss and hardness.", solution: "OmniCure AC Large (AC8-HD) high-dose UV LED, or NobleLight mercury arc for established flat-panel coating lines.", benefit: "Consistent, high-gloss finish cured in seconds with significantly reduced energy use versus mercury arc.", highlights: ["High-dose AC8-HD enables single-pass complete cure at conveyor speed", "Significant energy savings vs. legacy mercury arc systems", "Consistent gloss/hardness critical for furniture manufacturer quality standards"], recommended: "OmniCure AC Large (AC8-HD) or NobleLight Mercury Arc" },
  { id: "AN-WOD-002", industry: "Wood & Furniture Coatings", subCategory: "3D Profile & Edge", product: "AC Large with Multi-Angle Reflector", title: "3D Profile & Edge Coating", intro: "Contoured furniture profiles and edges create shadow areas with standard flat-lamp exposure geometry, requiring multi-angle coverage.", challenge: "Curing coatings on contoured furniture profiles and edges where standard flat exposure leaves shadow areas uncured.", solution: "OmniCure AC Large Series with multi-angle reflector array for complete coverage around profile contours.", benefit: "Full-coverage cure on complex 3D profiles, eliminating uncured shadow areas common with flat lamp arrays.", highlights: ["Multi-angle reflector array eliminates shadow-area undercure", "Suitable for routed edges, contoured profiles, and molded components", "Consistent cure across complex 3D furniture geometries"], recommended: "OmniCure AC Large with Multi-Angle Reflector" },
  { id: "AN-WOD-003", industry: "Wood & Furniture Coatings", subCategory: "Flooring", product: "AC Large LED Belt Conveyor (Multi-Stage)", title: "Parquet & Engineered Flooring UV Curing", intro: "Engineered wood flooring requires multi-layer UV coating cure at high production speed while maintaining wear-layer durability.", challenge: "Curing multi-layer UV coatings on engineered wood flooring at high production speeds while maintaining wear-layer durability.", solution: "OmniCure AC Large LED multi-stage belt conveyor system for sequential basecoat/topcoat cure.", benefit: "High-speed, multi-layer cure supporting durable, wear-resistant flooring finish production.", highlights: ["Multi-stage belt conveyor enables sequential basecoat/topcoat curing", "High-speed cure matches engineered flooring production line rates", "Wear-layer durability validated for residential/commercial flooring standards"], recommended: "OmniCure AC Large LED Belt Conveyor (Multi-Stage)" },
  { id: "AN-WOD-004", industry: "Wood & Furniture Coatings", subCategory: "Wood Print", product: "LX500 V2 Inline (Pin + Flood)", title: "UV Digital Print on Wood", intro: "Decorative panels and furniture fronts require digital print ink cure on wood substrates without raising grain or distorting the substrate.", challenge: "Curing UV digital print ink on wood substrates without raising grain or causing substrate distortion.", solution: "OmniCure LX500 V2 inline pinning plus flood cure stages for controlled, low-heat ink cure on wood.", benefit: "Sharp, distortion-free digital print on wood substrates suitable for decorative furniture applications.", highlights: ["Low-heat cure profile prevents wood grain raising or substrate warping", "Pin + flood stage combination preserves print sharpness through full cure", "Suitable for decorative furniture front and panel printing"], recommended: "OmniCure LX500 V2 Inline (Pin + Flood)" },
  { id: "AN-WOD-005", industry: "Wood & Furniture Coatings", subCategory: "Open Pore Finish", product: "AC Large LED Belt (Low Intensity)", title: "UV Penetrating Oil — Open Pore Finish", intro: "UV-curable penetrating oil finishes must cure within the wood pore structure without forming a surface film, preserving the natural wood feel.", challenge: "Curing UV-curable penetrating oil finishes that must cure within the wood pore structure without forming a surface film.", solution: "OmniCure AC Large LED belt conveyor at low-intensity setting for controlled, partial-depth cure.", benefit: "Authentic open-pore, natural wood-feel finish with UV-cure speed and durability benefits.", highlights: ["Low-intensity setting enables controlled, partial-depth cure", "Preserves authentic open-pore, natural wood tactile feel", "Combines traditional oil-finish aesthetics with UV-cure production speed"], recommended: "OmniCure AC Large LED Belt (Low Intensity)" },
  { id: "AN-WOD-006", industry: "Wood & Furniture Coatings", subCategory: "Anti-Fingerprint", product: "AC Large LED Belt Conveyor", title: "Anti-Fingerprint Soft-Touch Topcoat", intro: "Furniture and cabinetry surfaces increasingly specify soft-touch, anti-fingerprint topcoats that must preserve matte tactile finish through cure.", challenge: "Curing soft-touch, anti-fingerprint topcoats while preserving the matte, low-gloss tactile finish.", solution: "OmniCure AC Large LED belt conveyor for uniform cure of specialty soft-touch coating formulations.", benefit: "Durable, smudge-resistant matte finish cured at production line speed.", highlights: ["Uniform cure preserves specialty matte/soft-touch surface texture", "Smudge-resistant durability suitable for high-touch cabinetry surfaces", "Production line-speed cure for cabinetry and furniture manufacturers"], recommended: "OmniCure AC Large LED Belt Conveyor" },

  // ───────────── 9. METAL & INDUSTRIAL COATINGS (4) ─────────────
  { id: "AN-MET-001", industry: "Metal & Industrial Coatings", subCategory: "Powder Coating", product: "AC Large (AC8) or NobleLight Mercury Arc", title: "UV Powder Coating — Metal Parts", intro: "Heat-sensitive metal substrates (aluminum, MDF-metal hybrids) cannot tolerate conventional thermal powder coating ovens, driving adoption of UV powder cure.", challenge: "Curing UV powder coatings on heat-sensitive metal substrates that cannot tolerate conventional thermal cure ovens.", solution: "OmniCure AC Large (AC8) UV LED, or NobleLight mercury arc for high-dose powder coating cure.", benefit: "Full cure without the heat exposure of thermal powder coating ovens, enabling coating of heat-sensitive substrates.", highlights: ["High-dose AC8 enables full powder cure without thermal oven heat exposure", "Suitable for aluminum, MDF-metal hybrid, and other heat-sensitive substrates", "NobleLight mercury arc option for established powder coating line retrofit"], recommended: "OmniCure AC Large (AC8) or NobleLight Mercury Arc" },
  { id: "AN-MET-002", industry: "Metal & Industrial Coatings", subCategory: "Anti-Corrosion", product: "AC Large (AC7 or AC8) Belt Conveyor", title: "Metal Protective & Anti-Corrosion Coating", intro: "Industrial metal components require complete protective coating cure at production line speed to ensure long-term corrosion resistance.", challenge: "Curing protective anti-corrosion coatings on metal parts at production line speed while ensuring complete cure.", solution: "OmniCure AC Large Series (AC7/AC8) belt conveyor system for continuous, uniform protective coating cure.", benefit: "Complete, uniform cure supporting long-service-life corrosion protection on industrial metal components.", highlights: ["Continuous belt conveyor integration for production line speed cure", "Complete cure ensures long-term corrosion protection performance", "Scalable AC7/AC8 platform matches part size and coating thickness needs"], recommended: "OmniCure AC Large (AC7 or AC8) Belt Conveyor" },
  { id: "AN-MET-003", industry: "Metal & Industrial Coatings", subCategory: "Decorative Coating", product: "AC Large LED or LX500 V2 Array", title: "Decorative Metal Printing & Coating", intro: "Decorative UV ink and clear coat layers on metal substrates (appliances, signage, consumer goods) require high gloss and durability cured fast.", challenge: "Curing decorative UV ink and clear coat layers on metal substrates with high gloss and durability.", solution: "OmniCure AC Large LED or LX500 V2 array configuration for multi-pass decorative ink/coating cure.", benefit: "High-gloss, scratch-resistant decorative finish cured in a single fast pass.", highlights: ["Multi-pass array configuration accommodates multi-layer decorative builds", "High-gloss finish cured in a single fast pass increases throughput", "Suitable for appliance, signage, and consumer goods decorative finishing"], recommended: "OmniCure AC Large LED or LX500 V2 Array" },
  { id: "AN-MET-004", industry: "Metal & Industrial Coatings", subCategory: "Stamped Parts", product: "AC Large (AC8) Two-Stage Inline", title: "UV Primer + Basecoat for Stamped Metal Parts", intro: "Stamped metal automotive and appliance parts require sequential primer and basecoat cure without intercoat adhesion issues at inline speed.", challenge: "Curing primer and basecoat layers on stamped metal parts at two-stage inline speed without intercoat adhesion issues.", solution: "OmniCure AC Large (AC8) two-stage inline system for sequential primer-then-basecoat cure.", benefit: "Strong intercoat adhesion and full cure across both layers in a single continuous production pass.", highlights: ["Two-stage inline design ensures proper primer-to-basecoat adhesion sequence", "Single continuous pass eliminates intermediate handling steps", "Suitable for automotive and appliance stamped metal part finishing"], recommended: "OmniCure AC Large (AC8) Two-Stage Inline" },

  // ───────────── 10. AEROSPACE & DEFENSE (4) ─────────────
  { id: "AN-AER-001", industry: "Aerospace & Defense", subCategory: "Structural Composite", product: "S2000 Elite + R2000 Radiometer", title: "Structural Composite Bonding", hot: true, intro: "Flight-critical structural composite components require fully documented, NIST-traceable cure validation for airworthiness certification.", challenge: "Bonding structural composite components requiring documented, NIST-traceable cure validation for flight-critical parts.", solution: "OmniCure S2000 Elite with R2000 Radiometer for NIST-traceable dose calibration and full process documentation.", benefit: "Fully documented, repeatable structural bonding meeting aerospace quality and airworthiness certification requirements.", highlights: ["NIST-traceable calibration supports airworthiness certification documentation", "Closed-loop feedback ensures repeatable structural bond strength", "Suitable for carbon fiber and fiberglass composite bonding applications"], recommended: "OmniCure S2000 Elite + R2000 Radiometer" },
  { id: "AN-AER-002", industry: "Aerospace & Defense", subCategory: "Avionics PCB", product: "LX500 V2 or AC Small (AC4/AC5)", title: "PCB Conformal Coating — Avionics", hot: true, intro: "Avionics PCBs must meet MIL-I-46058C / IPC-CC-830B standards for altitude, vibration, humidity, and salt-fog environments.", challenge: "Protecting avionics PCBs to MIL-spec standards for altitude, vibration, humidity, and salt-fog environments.", solution: "OmniCure LX500 V2 or AC Small Series (AC4/AC5) for certified, repeatable conformal coating cure.", benefit: "MIL-spec-compliant protective coating cured in seconds, supporting avionics production and MRO turnaround.", highlights: ["MIL-I-46058C / IPC-CC-830B compatible coating cure process", "Fast cure supports both production and MRO turnaround timelines", "Repeatable process documentation for defense quality requirements"], recommended: "OmniCure LX500 V2 or AC Small (AC4/AC5)" },
  { id: "AN-AER-003", industry: "Aerospace & Defense", subCategory: "Airframe Sealing", product: "S2000 Elite (spot) or AC Large (area)", title: "Sealant Cure — Fuel Tank & Airframe", intro: "Airframe joints and integral fuel tank surfaces require validated, leak-free sealant cure for flight-critical integrity.", challenge: "Curing structural and fuel-resistant sealants on airframe joints and fuel tank surfaces requiring validated, leak-free cure.", solution: "OmniCure S2000 Elite for targeted spot sealant cure or AC Large for broader airframe seam area coverage.", benefit: "Leak-free, fuel-resistant seal cure validated for flight-critical airframe integrity.", highlights: ["Spot curing for targeted joint sealant application", "Area curing option for broader airframe seam coverage", "Validated for fuel-resistant, flight-critical seal performance"], recommended: "OmniCure S2000 Elite (spot) or AC Large (area)" },
  { id: "AN-AER-004", industry: "Aerospace & Defense", subCategory: "Space Electronics", product: "S2000 Elite + R2000 Radiometer", title: "Satellite & Space Electronics Encapsulation", intro: "Satellite and space-grade electronics require low-outgassing UV-curable encapsulants meeting NASA ASTM E595 outgassing standards.", challenge: "Encapsulating satellite electronics with low-outgassing materials meeting NASA ASTM E595 outgassing standards.", solution: "OmniCure S2000 Elite with R2000 Radiometer calibration for validated, low-outgassing encapsulant cure documentation.", benefit: "Documented, low-outgassing protection suitable for space-qualified electronics manufacturing.", highlights: ["NIST-traceable calibration supports space-qualification documentation", "Compatible with ASTM E595 low-outgassing encapsulant formulations", "Repeatable process control for space electronics reliability requirements"], recommended: "OmniCure S2000 Elite + R2000 Radiometer" },
];

import { appsZh, industryZh } from "./applicationNotes.zh";

// Returns the application note with Chinese fields merged in for the given
// locale; any field not translated falls back to the English source.
export function localizeApp(a: App, locale: "en" | "zh" | "vi" | "th"): App {
  if (locale !== "zh") return a;
  const zh = appsZh[a.id];
  return zh ? { ...a, ...zh } : a;
}

// Localized industry label for filter tabs / badges.
export function localizeIndustry(industry: string, locale: "en" | "zh" | "vi" | "th"): string {
  if (locale === "zh") return industryZh[industry] ?? industry;
  return industry;
}

// Readable, SEO-friendly slug for an application note's landing page.
export function appSlug(a: App): string {
  return a.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

export function getAppBySlug(slug: string): App | undefined {
  return apps.find((a) => appSlug(a) === slug);
}
