// Authoritative Excelitas UV curing product catalog.
// Organized by technology → brand. Used by the product index and detail pages.

export type Product = {
  slug: string;
  name: string;
  brand: string;
  brandId: "omnicure" | "phoseon" | "fusionuv" | "noblelight";
  tech: string;
  sub?: string;
  accent: string;
  intro: string;
  features: string[];
  applications: string[];
  specs: [string, string][];
  // Optional override link (e.g. products with a dedicated rich page)
  href?: string;
};

export const brandAccent: Record<Product["brandId"], string> = {
  omnicure: "#1A56DB",
  phoseon: "#0ea5e9",
  fusionuv: "#f59e0b",
  noblelight: "#7c3aed",
};

export const technologies = [
  "UV Spot Curing",
  "Water-Cooled UV LED Area Curing",
  "Air-Cooled UV LED Curing",
  "Microwave UV Curing",
];

export const products: Product[] = [
  // ───────────────── TECHNOLOGY 1: UV SPOT CURING ─────────────────
  {
    slug: "lx500",
    name: "OmniCure LX500 UV LED Spot Curing Controller",
    brand: "OmniCure®",
    brandId: "omnicure",
    tech: "UV Spot Curing",
    sub: "UV LED Spot",
    accent: "#44B549",
    intro:
      "The OmniCure® LX500 UV LED Spot Curing system controller is uniquely designed with proprietary Intelli-Lamp® technology that monitors LED head temperature and lifetime data, while automatically maintaining optical stability ±5% to provide greater process assurance. Available in either 2 or 4-channel configurations, the LX500 is the most flexible and cost-effective option for industrial manufacturing. The controller manages up to four UV LED Spot curing heads simultaneously or independently at wavelengths of 365, 385, 395 and 405 nm. The updated LX500 supports OmniCure's higher power V3 UV LED Heads delivering up to 27 W/cm² irradiance and up to 1,100 mW of optical power.",
    features: [
      "Multiple wavelengths at high irradiance: 17 W/cm² at 365 nm | 28 W/cm² at 385 nm | 27 W/cm² at 395 nm | 24 W/cm² at 405 nm",
      "Intelli-Lamp® LED technology: UV irradiation stability for power efficiency and long-term reliability over LED lifetime",
      "Precise light intensity control (5–100% in 1% increments) for consistent, repeatable UV process",
      "Simultaneous or individual control of up to four UV LED curing heads from a single controller",
      "Micro SD card interface: easy single-step programming; automatically saves exposure events and faults in real time",
      "StepCure®: customized multi-phase curing processes via controller or PC interface",
      "LED head temperature display for optimum efficiency and extended head lifetime",
      "~75% less energy consumption than a typical UV arc-lamp curing system",
      "Compact, robust design — no cooling required in dense, harsh manufacturing environments",
      "External control via optional foot pedal, PLC, or PC through USB communication",
      "CE and RoHS compliant",
    ],
    applications: [
      "Medical device manufacturing (catheters, cannulas, endoscopes, syringes)",
      "Electronics assembly (CCM, smartphones, tablets, micro-speakers, lenses)",
      "Optoelectronics assembly",
      "Automotive and aerospace component bonding",
      "Pharmaceutical, semiconductor and general-purpose UV adhesive curing",
      "EV battery manufacturing reliability improvement",
    ],
    specs: [
      ["UV LED Heads", "1 to 4 individual & interchangeable to any channel"],
      ["Mode Control", "4-Way membrane control for system display and programming"],
      ["Intensity Level", "5–100% (1% increments)"],
      ["Controller Dimensions", '(H) 5.5" × (W) 3.5" × (D) 5.5"'],
      ["External Control", "Optional foot pedal, PLC, or PC via USB"],
      ["Power Consumption", "72 W max at 120 VAC"],
      ["Ambient Temp/Humidity", "5° to 35°C, 85% max (no condensation)"],
      ["Storage Temp/Humidity", "-10° to 60°C, 85% max (no condensation)"],
      ["Certifications", "CE and RoHS compliant"],
      ["Warranty", "1 year"],
    ],
  },
  {
    slug: "v3-led-heads",
    name: "OmniCure V3 UV LED Heads",
    brand: "OmniCure®",
    brandId: "omnicure",
    tech: "UV Spot Curing",
    sub: "UV LED Spot",
    accent: "#44B549",
    intro:
      "Designed for use with the OmniCure LX500 Controller, the OmniCure V3 UV LED Heads feature next-generation high-output UV LEDs delivering best-in-class optical performance. With up to 120% increased optical power and up to 165% increase in peak irradiance compared to the predecessor MAX LED Heads, the V3 Heads deliver high dosage distributed uniformly across the spot area for faster, more consistent cures with greater control. Available in 365, 385, 395 and 405 nm wavelengths, delivering up to 22 W/cm² peak irradiance and 1,100 mW power with an exceptionally uniform beam profile.",
    features: [
      "Class-leading irradiance and optical power at 365, 385, 395 and 405 nm",
      "Up to 22 W/cm² peak irradiance and 1,100 mW total optical power",
      "Improved radiation distribution across the beam cross-section for consistent, controlled curing",
      "Up to 120% increased optical power vs. predecessor MAX LED Heads",
      "More energy efficient, lower maintenance, and longer service life",
      "Wide range of cross-compatible accessories: focusing lenses, adapters, extension cables",
      "Backward compatible with existing LX500 Controller",
      "Paired with LX500 for outstanding ±5% optical stability",
    ],
    applications: [
      "Precision UV adhesive curing in medical device assembly (catheters, endoscopes)",
      "Electronics: camera modules, smartphones, tablets, micro-speakers, lenses",
      "High-throughput industrial manufacturing requiring repeatable UV spot curing",
      "EV battery manufacturing adhesive bonding",
      "Optoelectronics assembly",
    ],
    specs: [
      ["Wavelengths", "365, 385, 395, 405 nm (standard); custom supported"],
      ["Peak Irradiance @ 365 nm", "17 W/cm² typical"],
      ["Peak Irradiance @ 385 nm", "28 W/cm² typical"],
      ["Peak Irradiance @ 395 nm", "27 W/cm² typical"],
      ["Peak Irradiance @ 405 nm", "24 W/cm² typical"],
      ["Maximum Optical Power", "Up to 1,100 mW"],
      ["Compatible Controller", "OmniCure LX500 (2- or 4-channel)"],
      ["Optical Stability", "±5% (via Intelli-Lamp® in LX500)"],
      ["vs Predecessor", "Up to 120% more power, up to 165% more irradiance"],
      ["Accessories", "Focusing lenses, adapters, extension cables"],
    ],
  },
  {
    slug: "ls200",
    name: "OmniCure LS200 UV LED Radiometry & Calibration System",
    brand: "OmniCure®",
    brandId: "omnicure",
    tech: "UV Spot Curing",
    sub: "UV LED Spot",
    accent: "#44B549",
    intro:
      "The OmniCure LS200 UV LED Radiometry and Calibration System ensures precise measurement and calibration of UV LED power or irradiance directly at the cure site, enabling manufacturers to control light output for a reliable, repeatable curing process. An enhanced version of its LS100 predecessor, the LS200 brings expanded measurement range and NRC-traceable sensor calibration. With accuracy of ±10% and resolution of 1 mW/cm² (irradiance) and 1 mW (power), the LS200 integrates seamlessly with the LX500 controller via the Beam Positioning Kit.",
    features: [
      "Measurement accuracy ±10%; resolution 1 mW/cm² (irradiance) and 1 mW (power)",
      "Wide measurement range: 1–2,000 mW (power) and 50 mW/cm²–40 W/cm² (irradiance)",
      "NRC-traceable factory calibration for accuracy and reliability",
      "Seamless integration with OmniCure LX500 via Beam Positioning Kit",
      "Selectable wavelengths programmable from 320–750 nm",
      "Sensor optimized for monochromatic LED sources",
      "Backward compatible with LS100",
      "Two versions: LS200 (irradiance, W/cm²) and LS200P (optical power, W)",
      "Compact sensor for measurements in confined curing areas",
      "USB connectivity to LM2011 light meter or LX500 for real-time measurement",
    ],
    applications: [
      "UV LED spot curing process control and calibration in electronics assembly",
      "Medical device manufacturing quality assurance and compliance",
      "Automotive UV adhesive curing process verification",
      "Defense and aerospace manufacturing UV process monitoring",
      "R&D and laboratory UV LED characterization",
    ],
    specs: [
      ["Measurement Accuracy", "±10%"],
      ["Irradiance Resolution", "1 mW/cm²"],
      ["Power Resolution", "1 mW"],
      ["Power Range", "1 mW to 2,000 mW"],
      ["Irradiance Range", "50 mW/cm² to 40 W/cm²"],
      ["Wavelength Range", "320–750 nm (selectable)"],
      ["Calibration Traceability", "NRC traceable"],
      ["Compatible Controller", "OmniCure LX500 (via Beam Positioning Kit)"],
      ["Communication", "USB to PC (LM2011 or LX500)"],
      ["Versions", "LS200 (irradiance) / LS200P (power)"],
    ],
  },
  {
    slug: "s2000-elite",
    name: "OmniCure S2000 Elite UV Spot Curing System",
    brand: "OmniCure®",
    brandId: "omnicure",
    tech: "UV Spot Curing",
    sub: "UV Lamp Spot",
    accent: "#1A56DB",
    href: "/product/omnicure/s2000",
    intro:
      "OmniCure® S2000 Elite is a new generation of lamp-based UV spot curing system designed for the most demanding manufacturing applications. Equipped with proprietary Closed-Loop Feedback and Intelli-Lamp® 2.0 technologies, it automatically monitors and maintains optical output within ±5%. The system features a high-speed mechanical shutter with 30 ms response and is Industry 4.0-ready with Ethernet, USB, SD card, NFC, and programmable PLC I/O.",
    features: [
      "Patented Closed-Loop Feedback (CLF): regulates UV output in real-time (±5% of set point)",
      "Intelli-Lamp® 2.0: 2,000 hours guaranteed, 3,500–4,000 hours typical lamp life",
      "High-speed mechanical shutter with 30 ms response time",
      "200-Watt UV lamp with outputs up to 30 W/cm²",
      "Industry 4.0 / IIoT ready: Ethernet, USB, SD card, NFC, programmable PLC I/O",
      "WEB UI for remote control and monitoring of single or multiple systems",
      "Field-interchangeable lamps and 7 optical band-pass filter options",
      "NIST-traceable calibration with OmniCure R2000 Radiometer",
      "Backward compatible with original S2000 XLA",
    ],
    applications: [
      "Medical device assembly: catheters, cannulas, blood oxygenators, syringes, endoscopes",
      "Electronics and optoelectronics precision adhesive curing",
      "Automated and semi-automated high-throughput manufacturing lines",
      "Academic, development and laboratory UV curing applications",
      "Industry 4.0 smart manufacturing requiring remote monitoring",
    ],
    specs: [
      ["Lamp Power", "200 Watt UV mercury lamp"],
      ["Output Irradiance", "Up to 30 W/cm²"],
      ["Shutter Response Time", "30 ms"],
      ["Optical Stability", "±5% of set point (Closed-Loop Feedback)"],
      ["Lamp Lifetime", "2,000 h guaranteed; 3,500–4,000 h typical"],
      ["Band-Pass Filters", "7 options (field-interchangeable)"],
      ["Communication", "Ethernet, USB, SD card, NFC, PLC I/O"],
      ["Remote Access", "WEB UI"],
      ["Calibration", "NIST-traceable via OmniCure R2000"],
    ],
  },
  {
    slug: "s1500-pro",
    name: "OmniCure S1500 Pro UV Spot Curing System",
    brand: "OmniCure®",
    brandId: "omnicure",
    tech: "UV Spot Curing",
    sub: "UV Lamp Spot",
    accent: "#1A56DB",
    intro:
      "The OmniCure® S1500 Pro is a revolutionary UV spot curing system designed for automated manufacturing. It features proprietary Intelli-Lamp® 2.0 technology for enhanced lamp life (2,000 hours guaranteed) and integrated StepCure® 2.0 for highly customizable multi-phase curing profiles. The intuitive 4.3\" LCD touch screen simplifies operation, while Industry 4.0 features include programmable PLC output, a Flight Recorder system event tracker, and Intelli-Tap NFC keycard capability.",
    features: [
      "Intelli-Lamp® 2.0: constantly monitors lamp parameters, optimizes lamp life (2,000 h guaranteed)",
      "StepCure® 2.0: precise programming of multi-phase curing profiles",
      '4.3" high-resolution LCD touch screen',
      "200-Watt UV lamp with outputs up to 30 W/cm²",
      "User-interchangeable optical filters (7 options) and lamp types",
      "Programmable PLC output (DB50 port)",
      "NFC with Intelli-Tap keycards (Admin, Supervisor levels)",
      "Flight Recorder system event tracking for Industry 4.0 traceability",
      "USB Type B and SD card connectivity",
      "Cleanroom-ready with dedicated duct attachment area",
      "Full backward compatibility with original S1500 light guides and radiometers",
    ],
    applications: [
      "High-throughput UV adhesive curing in micro-electronic manufacturing",
      "Automated bonding processes in opto-electronic manufacturing",
      "Medical device manufacturing requiring precision, traceability, and automation",
      "Cleanroom manufacturing environments",
      "General industrial automated manufacturing with UV spot curing requirements",
    ],
    specs: [
      ["Lamp Power", "200 Watt UV mercury lamp"],
      ["Output Irradiance", "Up to 30 W/cm²"],
      ["Display", '4.3" high-resolution LCD touch screen'],
      ["Lamp Lifetime", "2,000 hours guaranteed (Intelli-Lamp® 2.0)"],
      ["Band-Pass Filters", "7 options (user-interchangeable)"],
      ["PLC Interface", "DB50 port; 1 programmable output channel"],
      ["Communication", "USB Type B, SD card"],
      ["NFC", "Intelli-Tap keycards (Admin, Supervisor)"],
      ["Cleanroom Ready", "Yes (dedicated duct attachment area)"],
    ],
  },

  // ──────────── TECHNOLOGY 2: WATER-COOLED UV LED AREA (Phoseon) ────────────
  {
    slug: "nexus-ii",
    name: "Phoseon Nexus II Water-Cooled UV LED Large-Area System",
    brand: "Phoseon®",
    brandId: "phoseon",
    tech: "Water-Cooled UV LED Area Curing",
    accent: "#0d9488",
    intro:
      "The Nexus II™ water-cooled UV LED curing system is ideally suited for flexographic printing applications and delivers the best-performing solution in the industry. With patented thermal management techniques and ValidCure™ Technology, the Nexus II delivers the highest total UV energy for flexographic printing, bringing increased system reliability, improved performance in high-temperature environments, and an optional high-airflow model for enhanced cooling.",
    features: [
      "Patented thermal management for superior high-temperature performance",
      "ValidCure™ Technology for reliable, consistent UV output and process control",
      "Highest total UV energy output for flexographic printing in the industry",
      "Increased system reliability vs. previous generation",
      "Optional high-airflow model for enhanced cooling",
      "Water-cooled design for sustained high-performance operation",
    ],
    applications: [
      "Flexographic printing (primary application)",
      "Industrial UV LED area curing on production lines",
      "High-temperature environment UV curing",
      "Production lines requiring maximum UV output consistency",
    ],
    specs: [
      ["Cooling Method", "Water-cooled"],
      ["Technology", "UV LED"],
      ["Key Technology", "ValidCure™, patented thermal management"],
      ["Primary Application", "Flexographic printing"],
      ["Cooling Enhancement", "Optional high-airflow model"],
    ],
  },
  {
    slug: "fl200",
    name: "Phoseon FireLine FL200 UV LED Area Curing System",
    brand: "Phoseon®",
    brandId: "phoseon",
    tech: "Water-Cooled UV LED Area Curing",
    accent: "#0d9488",
    intro:
      "The FireLine™ FL200 is a compact and scalable water-cooled light source that operates with a separate controller. The lamps can be scaled to various lengths up to 2 meters and provide exceptional optical uniformity. The FL200 offers 25 W/cm² peak irradiance at 385/395/405 nm and 10 W/cm² at 365 nm — a high-performance light source ideal for medical device assembly and a wide range of UV LED area curing applications.",
    features: [
      "Compact and scalable design — up to 2 meters in length",
      "High peak irradiance: 25 W/cm² at 385/395/405 nm; 10 W/cm² at 365 nm",
      "Exceptional optical uniformity for consistent curing across the area",
      "Separate controller for flexible system integration",
      "Water-cooled for sustained high-performance, low-noise operation",
    ],
    applications: [
      "Medical device UV curing assembly",
      "Web and conveyor-based UV curing systems",
      "Large-area UV LED curing on production lines",
      "Applications requiring scalable UV curing up to 2 m width",
    ],
    specs: [
      ["Cooling Method", "Water-cooled"],
      ["Peak Irradiance @ 365 nm", "10 W/cm²"],
      ["Peak Irradiance @ 385/395/405 nm", "25 W/cm²"],
      ["Maximum Length", "Up to 2 meters (scalable)"],
      ["Controller", "Separate (not integrated)"],
      ["Technology", "UV LED"],
    ],
  },
  {
    slug: "fl400",
    name: "Phoseon FireLine FL400 UV LED Area Curing System",
    brand: "Phoseon®",
    brandId: "phoseon",
    tech: "Water-Cooled UV LED Area Curing",
    accent: "#0d9488",
    intro:
      "The FireLine™ FL400 is a water-cooled UV LED curing system designed for a wide variety of demanding printing and web/conveyor-based applications, including digital inkjet printing, container screen printing, and wood panel coating. It offers versatile connection options with straight or barbed water fittings and an enhanced window seal. Available in lengths from 125 mm to 350 mm, the FL400 delivers 8–24 W/cm² peak irradiance at 385/395/405 nm with Modbus TCP for remote access.",
    features: [
      "Versatile connection options: straight or barbed water fittings",
      "Enhanced window seal protecting against contaminants",
      "Available lengths: 125 mm to 350 mm",
      "Modbus TCP protocol for high-speed data exchange and remote access",
      "High peak irradiance: 8–24 W/cm² at 385, 395, 405 nm",
      "Water-cooled for sustained performance in demanding environments",
    ],
    applications: [
      "Digital inkjet printing",
      "Container screen printing",
      "Wood panel coating",
      "Web and conveyor-based UV curing",
      "Industrial large-area printing production lines",
    ],
    specs: [
      ["Cooling Method", "Water-cooled"],
      ["Peak Irradiance", "8–24 W/cm² at 385/395/405 nm"],
      ["Available Lengths", "125 mm to 350 mm"],
      ["Water Fittings", "Straight or barbed"],
      ["Communication", "Modbus TCP"],
      ["Technology", "UV LED"],
    ],
  },
  {
    slug: "fl400-i",
    name: "Phoseon FireLine FL400-i Industrial UV LED System",
    brand: "Phoseon®",
    brandId: "phoseon",
    tech: "Water-Cooled UV LED Area Curing",
    accent: "#0d9488",
    intro:
      "The FireLine™ FL400-i Industrial UV LED Area Curing System is specifically designed for demanding industrial coating and adhesive curing in harsh, high-contaminant environments such as pipe coating and metal finishing. It features a newly engineered IP66-rated enclosure with robust endcaps, advanced window sealing, and optional sacrificial glass to shield primary optics from heat, dust and impact — delivering the same industry-leading optical uniformity and high dose performance as the original FL400.",
    features: [
      "IP66-rated ruggedized enclosure for harsh, high-contaminant environments",
      "Advanced window sealing protects against heat, liquid, and dirt intrusion",
      "Versatile connection options: straight or barbed water fittings",
      "CDA (clean, dry air) ports to protect against condensation",
      "Optional sacrificial glass to shield primary optics",
      "Same optical uniformity and high dose performance as FL400",
      "Robust endcaps engineered for challenging industrial environments",
    ],
    applications: [
      "Pipe coating UV curing in industrial environments",
      "Metal finishing and surface coating curing",
      "Adhesive curing in high-contamination, high-temperature environments",
      "Applications requiring IP66-rated UV curing equipment",
    ],
    specs: [
      ["Cooling Method", "Water-cooled"],
      ["IP Rating", "IP66-compliant"],
      ["Water Fittings", "Straight or barbed"],
      ["Air Ports", "CDA ports for condensation protection"],
      ["Protection", "Optional sacrificial glass"],
      ["Base Performance", "Same as FL400"],
    ],
  },
  {
    slug: "fl440",
    name: "Phoseon FireLine FL440 UV LED Area Curing System",
    brand: "Phoseon®",
    brandId: "phoseon",
    tech: "Water-Cooled UV LED Area Curing",
    accent: "#0d9488",
    intro:
      "The FireLine™ FL440 complements the FireLine series by delivering unparalleled total UV energy. This IP66-compliant water-cooled UV LED system features a 40 mm-wide LED emitting window — significantly wider than the standard FL400 — providing longer exposure times and a greater dose of UV energy for complete single-pass curing. This eliminates the need for multiple passes and enhances production speed.",
    features: [
      "40 mm-wide LED emitting window for longer exposure and greater dose per pass",
      "IP66-compliant for robust operation in demanding environments",
      "Scalable to various lengths based on application requirements",
      "Exceptional optical uniformity across the entire curing area",
      "Single-pass complete curing capability — eliminates multiple passes",
      "Water-cooled design for sustained high-performance operation",
    ],
    applications: [
      "Demanding printing applications requiring maximum UV power",
      "Single-pass UV curing on high-speed production lines",
      "Industrial printing with wide-format exposure requirements",
      "Digital and commercial printing requiring maximum throughput",
    ],
    specs: [
      ["Cooling Method", "Water-cooled"],
      ["LED Window Width", "40 mm (vs 20 mm of standard FL400)"],
      ["Peak Irradiance", "16 W/cm² (40 mm window)"],
      ["IP Rating", "IP66-compliant"],
      ["Scalability", "Customizable to various lengths"],
      ["Key Advantage", "40 mm window enables single-pass curing"],
    ],
  },
  {
    slug: "vericure",
    name: "Phoseon VeriCure Water-Cooled UV LED Large-Area System",
    brand: "Phoseon®",
    brandId: "phoseon",
    tech: "Water-Cooled UV LED Area Curing",
    accent: "#0d9488",
    intro:
      "The VeriCure™ Water-Cooled UV LED curing system is a wide-format UV source engineered for demanding wood coating applications. Featuring a patented Semiconductor Light Matrix (SLM) array and a unique high-efficiency cooling design, the VeriCure delivers high optical power and outstanding dose performance for high-speed processing. Supporting conveyor line speeds up to 50 m/min, it represents a significant advancement in wood coating UV curing technology.",
    features: [
      "Patented Semiconductor Light Matrix (SLM) array for high optical power",
      "Patented SLM control technology for optimum uniformity",
      "Unique high-efficiency cooling design for outstanding dose performance",
      "Supports conveyor line speeds up to 50 m/min",
      "60% less energy consumption vs. conventional UV systems",
      "Optional secondary glass assembly to protect the emitting window",
      "Extensive communication: OmniCure AC Series, Analog, Modbus TCP/IP, Phoseon CLIP, Ethernet/PLC",
      "T-slot design for easy mounting and integration",
      "Eco-friendly: no mercury, no ozone",
      "Available wavelengths: 365, 395, 405 nm",
    ],
    applications: [
      "Wood coating — floors, furniture, panels (primary application)",
      "High-speed wide-format industrial coating applications",
      "Production lines requiring maximum dose at high line speeds",
      "Eco-conscious manufacturing (no mercury or ozone)",
    ],
    specs: [
      ["Cooling Method", "Water-cooled"],
      ["Core Technology", "Patented SLM array"],
      ["Available Wavelengths", "365, 395, 405 nm"],
      ["Max Conveyor Speed", "Up to 50 m/min"],
      ["Energy Savings", "~60% less than conventional UV"],
      ["Communication", "OmniCure AC, Analog, Modbus TCP/IP, CLIP, Ethernet/PLC"],
      ["Mounting", "T-slot"],
      ["Environmental", "No mercury, no ozone"],
    ],
  },

  // ──────────── TECHNOLOGY 3: AIR-COOLED UV LED ────────────
  {
    slug: "ac2",
    name: "OmniCure AC2 Series UV LED Small-Area System",
    brand: "OmniCure®",
    brandId: "omnicure",
    tech: "Air-Cooled UV LED Curing",
    sub: "Small-Area",
    accent: "#60a5fa",
    intro:
      "OmniCure® AC2 Series offers compact, air-cooled UV LED curing systems for small-area applications. With advanced front-end optics, the AC275 and AC2110 systems deliver over 2.5 W/cm² peak irradiance with exceptional uniformity. These compact solutions use patented individual UV LED module output to ensure consistent results over the entire curing area — suitable for curing inks, adhesives, and coatings in small-area manufacturing.",
    features: [
      "Advanced front-end optics delivering over 2.5 W/cm² peak irradiance",
      "Exceptional uniformity across the entire small curing area",
      "Patented individual UV LED module output for consistent results",
      "Compact and air-cooled — no chiller required",
      "Modular design suitable for both low- and high-power applications",
      "Available in AC275 and AC2110 configurations",
    ],
    applications: [
      "UV curing of inks, adhesives, and coatings in small-area applications",
      "Electronics and optoelectronics component bonding",
      "Medical device small-area UV curing",
      "Low- to high-power small-area curing (curing widths ≤75 mm)",
    ],
    specs: [
      ["Cooling Method", "Air-cooled (no chiller)"],
      ["Peak Irradiance", ">2.5 W/cm²"],
      ["Models", "AC275, AC2110"],
      ["Curing Width", "Small-area (≤75 mm)"],
      ["Technology", "UV LED, patented individual module output"],
    ],
  },
  {
    slug: "ac4",
    name: "OmniCure AC4 Series UV LED Small-Area System",
    brand: "OmniCure®",
    brandId: "omnicure",
    tech: "Air-Cooled UV LED Curing",
    sub: "Small-Area",
    accent: "#60a5fa",
    intro:
      "OmniCure® AC4 Series air-cooled UV LED curing systems are designed with high output LEDs and custom optics to deliver high irradiance of over 8 W/cm² with exceptional uniformity at long working distances. Consisting of the AC450, AC450P, AC475 and AC475P models, the AC4 Series is known for precise control of UV irradiance level and time, ensuring the correct dose of UV energy for a highly repeatable curing process.",
    features: [
      "High irradiance: over 8 W/cm² with exceptional uniformity",
      "Custom optics enabling high irradiance at long working distances",
      "Precise control of UV irradiance level and time for correct dose delivery",
      "Air-cooled — no chiller required",
      "Models: AC450, AC450P, AC475, AC475P ('P' = optical power measurement)",
      "Ensures highly repeatable UV curing process",
    ],
    applications: [
      "Small-area UV adhesive curing requiring high irradiance",
      "Electronic component bonding requiring precision and repeatability",
      "Medical device assembly",
      "UV curing at long working distances",
    ],
    specs: [
      ["Cooling Method", "Air-cooled (no chiller)"],
      ["Peak Irradiance", ">8 W/cm²"],
      ["Working Distance", "Extended long working distance"],
      ["Models", "AC450, AC450P, AC475, AC475P"],
      ["Curing Width", "Small-area (≤75 mm)"],
      ["Technology", "UV LED with custom optics"],
    ],
  },
  {
    slug: "ac5",
    name: "OmniCure AC5 Series UV LED Small-Area System",
    brand: "OmniCure®",
    brandId: "omnicure",
    tech: "Air-Cooled UV LED Curing",
    sub: "Small-Area",
    accent: "#60a5fa",
    intro:
      "OmniCure® AC5 Series air-cooled UV LED systems are designed for small-area curing with advanced front-end optics, delivering 14 W/cm² peak irradiance for fast, even curing. The series includes AC550, AC550P, AC575 and AC575P models, using OmniCure's patented LED UV module output for exceptional uniformity over the entire curing area. 'P' variants offer optical power (W) measurement for additional process verification.",
    features: [
      "High peak irradiance of 14 W/cm² for fast, even curing",
      "Advanced front-end optics for exceptional uniformity",
      "Patented LED UV module output ensures consistent results",
      "Air-cooled — no chiller required",
      "Models: AC550, AC550P, AC575, AC575P",
      "'P' variants include optical power (W) measurement capability",
    ],
    applications: [
      "Small-area UV curing requiring 14 W/cm² irradiance",
      "Electronic and optoelectronic component assembly",
      "Medical device bonding and sealing",
      "Applications requiring precise UV dose control and power measurement",
    ],
    specs: [
      ["Cooling Method", "Air-cooled (no chiller)"],
      ["Peak Irradiance", "14 W/cm²"],
      ["Models", "AC550, AC550P, AC575, AC575P"],
      ["Curing Width", "Small-area (≤75 mm)"],
      ["'P' Models", "Include optical power (W) measurement"],
    ],
  },
  {
    slug: "fe400",
    name: "Phoseon FireEdge FE400 UV LED Small-Area System",
    brand: "Phoseon®",
    brandId: "phoseon",
    tech: "Air-Cooled UV LED Curing",
    sub: "Small-Area",
    accent: "#60a5fa",
    intro:
      "The FireEdge™ FE400 air-cooled UV LED curing system offers advanced features with maximum flexibility, including built-in intensity control for both full-cure and UV inkjet pinning applications. It features patented Semiconductor Light Matrix (SLM) technology for process stability and is available in lengths from 80 mm to 240 mm. Segment control allows half the light source to be disabled for precise UV coverage, and a Hub can manage up to six light sources.",
    features: [
      "Built-in intensity control: full-cure, low-intensity (pinning), and half-source modes",
      "Patented SLM technology for process stability and repeatable output",
      "Available lengths: 80, 120, 160, 180, 240 mm",
      "Air-cooled — no water connections required",
      "Segment control: disable left or right half for precise UV coverage",
      "Scalable: stack end-to-end for contiguous uniform UV output",
      "Hub supports up to six light sources, managed as a single unit",
    ],
    applications: [
      "Digital inkjet printing (UV pinning and full cure)",
      "UV adhesive curing in electronics and optics assembly",
      "3D printing UV curing",
      "Coating curing in web and sheet-fed printing",
    ],
    specs: [
      ["Cooling Method", "Air-cooled"],
      ["Technology", "Solid-state UV LED with patented SLM"],
      ["Available Lengths", "80, 120, 160, 180, 240 mm"],
      ["Intensity Modes", "Full-cure, Low Intensity (pinning), Disable L/R SLM"],
      ["Power Supply", "External switching supply (Mean Well RSP-series)"],
      ["Multi-Lamp Control", "Hub: up to six sources as single unit"],
      ["Safety Rating", "Risk Group 3 per IEC 62471 at 200 mm"],
    ],
  },
  {
    slug: "fe410",
    name: "Phoseon FireEdge FE410 UV LED Small-Area System",
    brand: "Phoseon®",
    brandId: "phoseon",
    tech: "Air-Cooled UV LED Curing",
    sub: "Small-Area",
    accent: "#60a5fa",
    intro:
      "The FireEdge™ FE410 UV LED curing system provides up to 50% higher irradiance, power, and dose than the original FE400, making it ideal for faster processing speeds and enhanced throughput. Designed for full cure and pinning applications, it features patented TargetCure™ technology for precise and predictable UV output, built-in intensity control, and segment control. Units can be stacked end-to-end for contiguous, uniform UV output at any application size.",
    features: [
      "Up to 50% higher irradiance, power, and dose than the FE400",
      "Patented TargetCure™ technology for precise, predictable UV output",
      "Built-in intensity control for full-cure and pinning applications",
      "Segment control to save energy and achieve precise UV coverage",
      "Scalable: stackable end-to-end for contiguous uniform output",
      "Available lengths: 80, 120, 160, 180, 240 mm",
      "Air-cooled — no water connections required",
      "FE400 Hub backward compatible",
    ],
    applications: [
      "Digital inkjet printing — UV pinning and full cure",
      "3D printing UV curing at higher throughput",
      "UV adhesive curing in electronics and medical assembly",
      "Production lines upgrading from FE400 seeking enhanced throughput",
    ],
    specs: [
      ["Cooling Method", "Air-cooled"],
      ["Technology", "Solid-state UV LED with patented TargetCure™"],
      ["vs FE400", "Up to 50% higher irradiance, power, and dose"],
      ["Available Lengths", "80, 120, 160, 180, 240 mm"],
      ["Intensity Modes", "Full-cure, Low Intensity (pinning), Disable L/R SLM"],
      ["Power Supply", "External switching supply"],
      ["Safety Rating", "Risk Group 3 per IEC 62471 at 200 mm"],
    ],
  },
  {
    slug: "fj800",
    name: "Phoseon FireJet FJ800 UV LED Large-Area System",
    brand: "Phoseon®",
    brandId: "phoseon",
    tech: "Air-Cooled UV LED Curing",
    sub: "Large-Area",
    accent: "#1A56DB",
    intro:
      "The Phoseon FireJet™ FJ800 UV LED Curing System is a large-area curing solution for adhesive and coating applications requiring low irradiance and long dwell time on large-scale production lines. Starting with a 100 mm × 100 mm base curing area, the modular components scale in all four directions, providing contiguous, uniform UV illumination. Operated by a simple controller supporting up to six light sources, the FJ800 is available in 365 and 395 nm wavelengths.",
    features: [
      "Modular and scalable: 100 mm × 100 mm base, scalable in all four directions",
      "Contiguous, uniform UV output across the entire curing area",
      "Simple controller supporting up to six light sources",
      "Available wavelengths: 365, 395 nm",
      "Air-cooled for flexible, cost-effective integration",
      "Optimized for large-area curing requiring low irradiance and long dwell time",
    ],
    applications: [
      "Micro-speaker manufacturing (adhesive curing)",
      "Camera module (CCM) assembly",
      "Flat panel display manufacturing",
      "Medical device assembly requiring large-area UV curing",
      "Large-scale electronics production lines",
    ],
    specs: [
      ["Cooling Method", "Air-cooled"],
      ["Base Curing Area", "100 mm × 100 mm (scalable all directions)"],
      ["Peak Irradiance @ 365 nm", "0.6 W/cm²"],
      ["Peak Irradiance @ 395 nm", "1.0 W/cm²"],
      ["Available Wavelengths", "365, 395 nm"],
      ["Controller", "Graphical interface; up to 6 sources"],
      ["Working Distance", "10–20 mm"],
    ],
  },
  {
    slug: "fj801",
    name: "Phoseon FireJet FJ801 UV LED Large-Area System",
    brand: "Phoseon®",
    brandId: "phoseon",
    tech: "Air-Cooled UV LED Curing",
    sub: "Large-Area",
    accent: "#1A56DB",
    intro:
      "The Phoseon FireJet™ FJ801 UV LED Large-Area Curing Systems are designed primarily for production lines requiring area curing, such as micro-speaker and camera module manufacturing. These modular products scale from a 100 mm × 100 mm base and feature patented TargetCure™ technology for precise and predictable UV output. Available in 365, 385, 395 and 405 nm — a wider selection than the FJ800. The FJ801 controller is backward compatible with the FJ800 lamp.",
    features: [
      "Patented TargetCure™ technology for precise, predictable UV output",
      "Modular and scalable: 100 mm × 100 mm base, scalable in all directions",
      "Available wavelengths: 365, 385, 395, 405 nm (wider than FJ800)",
      "FJ801 controller backward compatible with FJ800 lamp",
      "Air-cooled for flexible integration without chiller",
      "Contiguous and uniform UV output across the curing area",
    ],
    applications: [
      "Micro-speaker manufacturing",
      "Camera module (CCM) assembly",
      "Electronics manufacturing requiring large-area UV curing",
      "Medical device assembly",
      "Production lines upgrading from FJ800",
    ],
    specs: [
      ["Cooling Method", "Air-cooled"],
      ["Base Curing Area", "100 mm × 100 mm (scalable)"],
      ["Available Wavelengths", "365, 385, 395, 405 nm"],
      ["Key Technology", "Patented TargetCure™"],
      ["Controller Compatibility", "Backward compatible with FJ800 lamps"],
      ["Working Distance", "10 mm"],
    ],
  },

  // ──────────── TECHNOLOGY 4: MICROWAVE UV CURING ────────────
  {
    slug: "f-series",
    name: "Fusion UV F Series Microwave UV Curing Systems",
    brand: "Fusion UV®",
    brandId: "fusionuv",
    tech: "Microwave UV Curing",
    sub: "F Series",
    accent: "#f59e0b",
    intro:
      "The Fusion UV F Series are production-proven, simple-to-use microwave-powered systems used in hundreds of industrial UV curing applications worldwide. The F Series features electrodeless UV bulbs available in a variety of wavelengths, allowing optimization to specific process needs. Because these systems are electrode-free, they avoid the degradation issues of traditional UV lamps, extending lamp life and reducing maintenance. The modular design provides process flexibility with lower cost of ownership and easily retrofits into existing production lines. Note: lamps contain mercury — manage per applicable disposal laws.",
    features: [
      "Production-proven, simple-to-use design for broad industrial applications",
      "Electrodeless bulb design: avoids electrode degradation, extends lamp life",
      "Multiple UV broadband wavelengths (D, H, V, Q, M bulb fills)",
      "Easy-to-service modular design for lower cost of ownership",
      "Easily retrofits into existing production lines",
      "Multiple power classes: F300 (3 kW) and F600 (6 kW)",
      "High-intensity UV output for fast, uniform curing",
      "Wide selection of accessories and replacement parts",
    ],
    applications: [
      "Industrial UV curing of adhesives, coatings, and inks",
      "Optical fiber coating curing",
      "Wire and cable coating and marking",
      "Printing and converting applications",
      "Electronics and medical device UV adhesive curing",
    ],
    specs: [
      ["Power Classes", "F300 (3 kW), F600 (6 kW)"],
      ["Bulb Type", "Electrodeless UV bulb"],
      ["Bulb Fills", "D, H, V, Q, M spectral fills"],
      ["Technology", "Microwave-powered electrodeless lamp"],
      ["Design", "Modular for easy servicing"],
      ["Accessories", "Bulbs, reflectors, panes, magnetrons"],
      ["Mercury", "Yes — manage per disposal laws"],
    ],
  },
  {
    slug: "lighthammer-6",
    name: "Fusion UV LightHammer 6 MARK II UV Curing System",
    brand: "Fusion UV®",
    brandId: "fusionuv",
    tech: "Microwave UV Curing",
    sub: "LightHammer Series",
    accent: "#f59e0b",
    intro:
      "The Fusion UV LightHammer® 6 MARK II is a smart microwave-powered UV curing system with a 150 mm (6 inch) irradiator and 200 W/cm (500 W/inch) power class. Engineered for precision and lowest cost of ownership, it delivers high-intensity UV curing in a compact 6-inch module. The system includes an irradiator, electrodeless UV bulb, and a solid-state power supply with internal or external cooling blower. Modular systems can be combined to cure across wider widths or around complex shaped surfaces.",
    features: [
      "Smart solid-state power supply: flexible software-based control, reduced operating costs",
      "Power Factor Correction >99% at full load — eliminates electrical harmonics",
      "Reduced weight and better airflow for efficient cooling",
      "Modular design: combine systems for wider widths or complex surfaces",
      "Available with internal or external cooling blower",
      "150 mm (6 inch) irradiator with 200 W/cm (500 W/inch) power class",
      "Smaller and lighter than previous generation for easy integration",
      "Mercury-containing bulbs — manage per disposal laws",
    ],
    applications: [
      "High-speed converting, printing, and coating production lines",
      "Electronics and automotive UV adhesive curing",
      "Fiber optics and medical device UV curing",
      "Industrial lines requiring modular, scalable UV curing width",
    ],
    specs: [
      ["Irradiator Width", "150 mm (6 inch)"],
      ["Power Class", "200 W/cm (500 W/inch)"],
      ["Power Supply", "Solid-state (smart)"],
      ["Power Factor Correction", ">99% at full load"],
      ["Cooling", "Internal or external cooling blower"],
      ["Bulb Type", "Electrodeless UV bulb (D, H, V, Q, M)"],
      ["Modularity", "Combinable for wider curing width"],
      ["Mercury", "Yes — manage per disposal laws"],
    ],
  },
  {
    slug: "lighthammer-10",
    name: "Fusion UV LightHammer 10 MARK III UV Curing System",
    brand: "Fusion UV®",
    brandId: "fusionuv",
    tech: "Microwave UV Curing",
    sub: "LightHammer Series",
    accent: "#f59e0b",
    intro:
      "The Fusion UV LightHammer® 10 MARK III is the most advanced smart, IoT-ready, microwave-powered UV curing system, featuring a 10-inch irradiator and 240 W/cm (600 W/inch) power class. With sensors in both the intelligent irradiator and the solid-state power supply, it is fully IoT-enabled for today's Digitization Roadmap, monitoring 8 real-time operating parameters to minimize downtime and optimize processes. The intelligent irradiator is a direct drop-in replacement for existing LHI10 Mark II irradiators. Optional AIMS® software provides centralized real-time monitoring.",
    features: [
      "IoT-ready: sensors in both irradiator and power supply for real-time monitoring",
      "Intelligent irradiator measures 8 operating parameters",
      "Reduces total cost of ownership via increased uptime",
      "240 W/cm (600 W/in) — highest power class in the LightHammer series",
      "Smart solid-state power supply with software-based control",
      "Optional AIMS® software for centralized monitoring",
      "Direct drop-in replacement for existing LHI10 Mark II irradiators",
      "Systems combinable to increase curing width or cure complex 3D surfaces",
      "Available in D, H, H+, M, Q, V bulb spectral fills",
      "Mercury-containing bulbs — manage per disposal laws",
    ],
    applications: [
      "Converting, printing, and high-speed coating production lines",
      "Electronics, automotive, and fiber optics UV curing",
      "Medical device UV adhesive curing",
      "Industry 4.0 / smart manufacturing requiring IoT monitoring",
    ],
    specs: [
      ["Irradiator Footprint", "266.7 mm × 200 mm"],
      ["Power Class", "240 W/cm (600 W/inch)"],
      ["Line Power at 100%", "10 kVA"],
      ["Input Voltages", "200–480 V auto-ranging, 3-phase, 50/60 Hz"],
      ["Bulb Length", "25 cm"],
      ["Bulb Fills", "D, H, H+, M, Q, V"],
      ["Sensors", "8 operating parameters"],
      ["Weight", "LHI10 Mark III: 19 kg; LHI10B: 28 kg"],
      ["Monitoring Software", "Optional AIMS®"],
      ["Mercury", "Yes — manage per disposal laws"],
    ],
  },
  {
    slug: "drf-series",
    name: "DRF Series Optical Fiber UV Curing Systems",
    brand: "Noblelight®",
    brandId: "noblelight",
    tech: "Microwave UV Curing",
    sub: "Optical Fiber",
    accent: "#7c3aed",
    intro:
      "The Fusion UV DRF Series cure photoresponsive coatings, coloring inks, and ribbon matrix polymers in the production of optical fiber and cable. The DRF Series has been the UV curing system of choice for fiber manufacturing worldwide, thanks to its patented secondary elliptical reflector system that delivers highly focused, intense UV energy. The optical fiber passes through a sealed quartz tube aligned at the secondary focal point of the elliptical reflector for full-surface UV exposure. DRF systems support power levels from 1.8 kW (F300S) to 6 kW.",
    features: [
      "Patented secondary elliptical reflector: highest UV irradiance per watt",
      "Highly focused, intense UV energy for optical fiber curing",
      "Sealed quartz tube enables full-surface UV exposure with minimal stray radiation",
      "Noblelight microwave-powered electrodeless lamp: stable, consistent UV output",
      "Reaches maximum curing power within seconds of ignition",
      "Modular design for easy maintenance and component replacement",
      "Interchangeable bulbs to match spectral output to coating needs",
      "Optional easy-align lamp mounting system",
      "Optional patented back reflector for enhanced UV efficiency",
      "Individual lamp switching in multi-lamp setups for line-speed adjustment",
    ],
    applications: [
      "Optical fiber coating production — photoresponsive coatings on fiber",
      "Coloring inks for optical fiber color coding",
      "Ribbon matrix polymer curing for fiber optic ribbon cable",
      "Draw tower UV curing systems",
      "Wire and cable UV coating and marking",
    ],
    specs: [
      ["Models", "DRF F6 (6-inch), DRF F10T (10-inch)"],
      ["Power Range", "1.8 kW (F300S) to 6 kW"],
      ["Power Level Options", "65%/100% fixed or 35%–100% variable"],
      ["Reflector Types", "R500 (full-spectrum) or Dichroic (blocks visible/IR)"],
      ["Cooling", "Air-cooled (push-pull airflow)"],
      ["Quartz Tube Sealing", "Teflon® gasket isolation"],
      ["Lamp Type", "Noblelight microwave-powered electrodeless"],
      ["Mercury", "Yes — manage per disposal laws"],
    ],
  },
];

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

// Maps the model chips shown on the Products brand selector to catalog slugs,
// so each real product chip can link to its detail page.
export const modelToSlug: Record<string, string> = {
  "S2000 Elite": "s2000-elite",
  "S1500 Pro": "s1500-pro",
  "LX500 V2": "lx500",
  "LS200 Radiometer": "ls200",
  "UV LED Heads (V3)": "v3-led-heads",
  "AC2": "ac2",
  "AC5": "ac5",
  "Nexus II": "nexus-ii",
  "FireLine FL200": "fl200",
  "FireLine FL400": "fl400",
  "FireLine FL400-i Industrial": "fl400-i",
  "FireLine FL440": "fl440",
  "VeriCure Water-Cooled": "vericure",
  "FireJet FJ800": "fj800",
  "FireJet FJ801": "fj801",
  "FireEdge FE400": "fe400",
  "FireEdge FE410": "fe410",
  "LightHammer 6 Mark II": "lighthammer-6",
  "LightHammer 10 Mark III": "lighthammer-10",
  "F Series": "f-series",
  "Optical Fiber UV Systems": "drf-series",
};

export function productHref(p: Product): string {
  return p.href ?? `/product/systems/${p.slug}`;
}

// Product hero images live in the COS bucket under IMAGE/products/.
// The object keys there do NOT follow the slug convention (and are
// case-sensitive), so we map each slug to its real filename explicitly.
const PRODUCT_IMG_BASE =
  "https://etiatech-1303055923.cos.ap-singapore.myqcloud.com/IMAGE/products";

// slug → actual object key in the bucket.
const productImageFile: Record<string, string> = {
  "lx500": "LX500.png",
  "v3-led-heads": "V3.png",
  "ls200": "LS200.png",
  "s2000-elite": "S2E.png",
  "s1500-pro": "S1500.png",
  "nexus-ii": "nexusII.png",
  "fl200": "fl200.png",
  "fl400": "fl400.png",
  "fl400-i": "fl400i.png",
  "fl440": "fl440.png",
  "ac2": "AC2.png",
  "ac4": "AC4.png",
  "ac5": "AC5.png",
  "fj800": "fj800.png",
  "fj801": "fj801.png",
  "f-series": "f300.png",
  "lighthammer-6": "6markII.png",
  "lighthammer-10": "10markIII.png",
  // No asset yet in the bucket for: vericure, fe400, fe410, drf-series.
};

// Full image URL for a product, or "" when no asset is available (the UI
// renders a branded placeholder instead of a broken image in that case).
export function productImage(p: Product): string {
  const file = productImageFile[p.slug];
  return file ? `${PRODUCT_IMG_BASE}/${encodeURIComponent(file)}` : "";
}
