// Chinese translations for product spec-table LABELS (the left column only).
// Spec values stay language-neutral (numbers, units, model names). Any label
// not present here falls back to its English source.
export const specLabelZh: Record<string, string> = {
  "'P' Models": "「P」型号",
  "48 V Power In (max)": "48V 输入功率（最大）",
  "48 VDC Power In (max)": "48VDC 输入功率（最大）",
  "Accessories": "配件",
  "Accessory For": "适配于",
  "Adjoining": "拼接",
  "Air Ports": "气路接口",
  "Ambient Operating Temperature": "环境工作温度",
  "Ambient Temp/Humidity": "环境温度/湿度",
  "Amperage / Power (±10%)": "电流 / 功率（±10%）",
  "Available Lengths": "可选长度",
  "Available Wavelengths": "可选波长",
  "Band-Pass Filters": "带通滤光片",
  "Base Curing Area": "基础固化面积",
  "Base Performance": "基础性能",
  "Brand / Series": "品牌 / 系列",
  "Bulb Fills": "灯泡填充物",
  "Bulb Length": "灯泡长度",
  "Bulb Type": "灯泡类型",
  "Calibration": "校准",
  "Calibration Traceability": "校准溯源",
  "Certifications": "认证",
  "Cleanroom Ready": "洁净室适用",
  "Communication": "通信",
  "Compatible Controller": "兼容控制器",
  "Compatible OmniCure Systems": "兼容 OmniCure 系统",
  "Compatible Systems": "兼容系统",
  "Configuration": "配置",
  "Connector": "连接器",
  "Control": "控制",
  "Controller": "控制器",
  "Controller Compatibility": "控制器兼容性",
  "Cooling": "冷却",
  "Cooling Enhancement": "冷却增强",
  "Cooling Method": "冷却方式",
  "Cross Section": "截面尺寸",
  "Cure-Ring Adapter": "固化环适配器",
  "Collimating Adapter": "准直适配器",
  "Controller Dimensions": "控制器尺寸",
  "Dimensions (L×W×H)": "尺寸（长×宽×高）",
  "Display": "显示屏",
  "Light-Line Adapter": "线光适配器",
  "Curing Coverage": "固化覆盖",
  "Curing Width": "固化宽度",
  "Curing Width (AC9225/P)": "固化宽度（AC9225/P）",
  "Curing Widths": "固化宽度",
  "Custom Sensor Support": "定制传感器支持",
  "DC Connector Type": "直流连接器类型",
  "Design": "设计",
  "Detector": "探测器",
  "Emission Length": "发光长度",
  "Emission Window": "发光窗口",
  "Emission Window Size": "发光窗口尺寸",
  "Emitting Widths": "发光宽度",
  "Emitting Window": "发光窗口",
  "Energy Savings": "节能",
  "Ethernet Interface": "以太网接口",
  "Expected LED Lifetime": "预期 LED 寿命",
  "External Control": "外部控制",
  "Family": "系列",
  "Fiber Options": "光纤选项",
  "Full AC9 Series Widths": "AC9 系列全部宽度",
  "Generation": "代次",
  "Humidity Range": "湿度范围",
  "IP Rating": "IP 防护等级",
  "Input Voltage": "输入电压",
  "Input Voltages": "输入电压",
  "Integration": "集成",
  "Intensity Level": "强度等级",
  "Intensity Modes": "强度模式",
  "Irradiance @ 365 nm": "辐照度 @ 365 nm",
  "Irradiance @ 385 nm": "辐照度 @ 385 nm",
  "Irradiance @ 395 nm": "辐照度 @ 395 nm",
  "Irradiance @ 405 nm": "辐照度 @ 405 nm",
  "Irradiance Range": "辐照度范围",
  "Irradiance Resolution": "辐照度分辨率",
  "Irradiator Footprint": "辐照器占位尺寸",
  "Irradiator Width": "辐照器宽度",
  "Key Advantage": "主要优势",
  "Key Advantage vs FJ100": "相较 FJ100 的主要优势",
  "Key Technology": "核心技术",
  "LED Lifetime": "LED 寿命",
  "LED Window Width": "LED 窗口宽度",
  "Lamp Lifetime": "灯泡寿命",
  "Lamp Power": "灯泡功率",
  "Lamp Type": "灯泡类型",
  "Length": "长度",
  "Line Power at 100%": "100% 时线路功率",
  "Liquid Light Guide Lengths": "液体导光管长度",
  "Liquid Light Guide Tips": "液体导光管端头",
  "Max Operating Temperature": "最高工作温度",
  "Maximum Dimensions": "最大尺寸",
  "Maximum Fan Capacity": "最大风扇风量",
  "Maximum Length": "最大长度",
  "Maximum Optical Power": "最大光功率",
  "Measurement Accuracy": "测量精度",
  "Measurement Type": "测量类型",
  "Mercury": "汞",
  "Minimum Clearance": "最小间隙",
  "Mode Control": "模式控制",
  "Models": "型号",
  "Modularity": "模块化",
  "Monitoring Software": "监控软件",
  "Multi-Lamp Control": "多灯控制",
  "Multi-Leg Configurations": "多腿配置",
  "Multi-Station Use": "多工位使用",
  "NFC": "NFC",
  "Operating Environment": "工作环境",
  "Operating Voltage": "工作电压",
  "Optical Stability": "光学稳定性",
  "Optics": "光学",
  "Outer Dimensions": "外形尺寸",
  "Outer Window": "外窗口",
  "Output Irradiance": "输出辐照度",
  "PLC Interface": "PLC 接口",
  "Peak Irradiance": "峰值辐照度",
  "Peak Irradiance @ 365 nm": "峰值辐照度 @ 365 nm",
  "Peak Irradiance @ 385 nm": "峰值辐照度 @ 385 nm",
  "Peak Irradiance @ 385/395/405 nm": "峰值辐照度 @ 385/395/405 nm",
  "Peak Irradiance @ 395 nm": "峰值辐照度 @ 395 nm",
  "Peak Irradiance @ 405 nm": "峰值辐照度 @ 405 nm",
  "Peak Irradiance at Fiber": "光纤处峰值辐照度",
  "Peak Wavelength": "峰值波长",
  "Peak Wavelengths": "峰值波长",
  "Power Cable": "电源线缆",
  "Power Class": "功率等级",
  "Power Classes": "功率等级",
  "Power Consumption": "功耗",
  "Power Factor Correction": "功率因数校正",
  "Power Level Options": "功率档位选项",
  "Power Range": "功率范围",
  "Power Resolution": "功率分辨率",
  "Power Supply": "电源",
  "Power Supply (Included)": "电源（含）",
  "Primary Application": "主要应用",
  "Primary Applications": "主要应用",
  "Protection": "防护",
  "Quartz Tube Sealing": "石英管密封",
  "Radiance at Target": "目标处辐射度",
  "Real-Time Calibration": "实时校准",
  "Reflector Types": "反射器类型",
  "Remote Access": "远程访问",
  "Remote Ethernet Functions": "远程以太网功能",
  "Safety Rating": "安全等级",
  "Scalability": "可扩展性",
  "Sensors": "传感器",
  "Shutter Response Time": "快门响应时间",
  "Storage Temp/Humidity": "存储温度/湿度",
  "Storage Temperature": "存储温度",
  "Switching": "开关切换",
  "Technology": "技术",
  "Type": "类型",
  "Typical Dose": "典型剂量",
  "Typical UV Emitting Power": "典型 UV 发射功率",
  "UV Energy Advantage": "UV 能量优势",
  "UV LED Head": "UV LED 灯头",
  "UV LED Heads": "UV LED 灯头",
  "UV Power": "UV 功率",
  "UV Power @ 365 nm (75 mm)": "UV 功率 @ 365 nm（75 mm）",
  "UV Power @ 405 nm / 16 W/cm² (375 mm)": "UV 功率 @ 405 nm / 16 W/cm²（375 mm）",
  "Versions": "版本",
  "Warranty": "保修",
  "Water Fittings": "水路接口",
  "Wavelength Range": "波长范围",
  "Wavelengths": "波长",
  "Weight": "重量",
  "Window Dimensions": "窗口尺寸",
  "Window Lengths": "窗口长度",
  "Window Width": "窗口宽度",
  "Working Distance": "工作距离",
  "vs FE400": "相较 FE400",
  "vs Predecessor": "相较前代",
};

// Vietnamese translations for product spec-table LABELS (same keys as specLabelZh).
export const specLabelVi: Record<string, string> = {
  "'P' Models": "Model 'P'",
  "48 V Power In (max)": "Công suất đầu vào 48 V (tối đa)",
  "48 VDC Power In (max)": "Công suất đầu vào 48 VDC (tối đa)",
  "Accessories": "Phụ kiện",
  "Accessory For": "Phụ kiện cho",
  "Adjoining": "Ghép nối",
  "Air Ports": "Cổng khí",
  "Ambient Operating Temperature": "Nhiệt độ hoạt động môi trường",
  "Ambient Temp/Humidity": "Nhiệt độ/Độ ẩm môi trường",
  "Amperage / Power (±10%)": "Dòng điện / Công suất (±10%)",
  "Available Lengths": "Chiều dài có sẵn",
  "Available Wavelengths": "Bước sóng có sẵn",
  "Band-Pass Filters": "Bộ lọc thông dải",
  "Base Curing Area": "Diện tích đóng rắn cơ bản",
  "Base Performance": "Hiệu suất cơ bản",
  "Brand / Series": "Thương hiệu / Dòng sản phẩm",
  "Bulb Fills": "Chất nạp bóng đèn",
  "Bulb Length": "Chiều dài bóng đèn",
  "Bulb Type": "Loại bóng đèn",
  "Calibration": "Hiệu chuẩn",
  "Calibration Traceability": "Khả năng truy xuất hiệu chuẩn",
  "Certifications": "Chứng nhận",
  "Cleanroom Ready": "Sẵn sàng cho phòng sạch",
  "Communication": "Truyền thông",
  "Compatible Controller": "Bộ điều khiển tương thích",
  "Compatible OmniCure Systems": "Hệ thống OmniCure tương thích",
  "Compatible Systems": "Hệ thống tương thích",
  "Configuration": "Cấu hình",
  "Connector": "Đầu nối",
  "Control": "Điều khiển",
  "Controller": "Bộ điều khiển",
  "Controller Compatibility": "Khả năng tương thích bộ điều khiển",
  "Cooling": "Làm mát",
  "Cooling Enhancement": "Tăng cường làm mát",
  "Cooling Method": "Phương pháp làm mát",
  "Cross Section": "Tiết diện",
  "Cure-Ring Adapter": "Bộ chuyển đổi vòng đóng rắn",
  "Collimating Adapter": "Bộ chuyển đổi chuẩn trực",
  "Controller Dimensions": "Kích thước bộ điều khiển",
  "Dimensions (L×W×H)": "Kích thước (L×W×H)",
  "Display": "Màn hình",
  "Light-Line Adapter": "Bộ chuyển đổi đường sáng",
  "Curing Coverage": "Phạm vi đóng rắn",
  "Curing Width": "Chiều rộng đóng rắn",
  "Curing Width (AC9225/P)": "Chiều rộng đóng rắn (AC9225/P)",
  "Curing Widths": "Chiều rộng đóng rắn",
  "Custom Sensor Support": "Hỗ trợ cảm biến tùy chỉnh",
  "DC Connector Type": "Loại đầu nối DC",
  "Design": "Thiết kế",
  "Detector": "Bộ dò",
  "Emission Length": "Chiều dài phát xạ",
  "Emission Window": "Cửa sổ phát xạ",
  "Emission Window Size": "Kích thước cửa sổ phát xạ",
  "Emitting Widths": "Chiều rộng phát xạ",
  "Emitting Window": "Cửa sổ phát xạ",
  "Energy Savings": "Tiết kiệm năng lượng",
  "Ethernet Interface": "Giao diện Ethernet",
  "Expected LED Lifetime": "Tuổi thọ LED dự kiến",
  "External Control": "Điều khiển bên ngoài",
  "Family": "Dòng sản phẩm",
  "Fiber Options": "Tùy chọn cáp quang",
  "Full AC9 Series Widths": "Chiều rộng toàn dòng AC9",
  "Generation": "Thế hệ",
  "Humidity Range": "Phạm vi độ ẩm",
  "IP Rating": "Cấp bảo vệ IP",
  "Input Voltage": "Điện áp đầu vào",
  "Input Voltages": "Điện áp đầu vào",
  "Integration": "Tích hợp",
  "Intensity Level": "Mức cường độ",
  "Intensity Modes": "Chế độ cường độ",
  "Irradiance @ 365 nm": "Cường độ bức xạ @ 365 nm",
  "Irradiance @ 385 nm": "Cường độ bức xạ @ 385 nm",
  "Irradiance @ 395 nm": "Cường độ bức xạ @ 395 nm",
  "Irradiance @ 405 nm": "Cường độ bức xạ @ 405 nm",
  "Irradiance Range": "Phạm vi cường độ bức xạ",
  "Irradiance Resolution": "Độ phân giải cường độ bức xạ",
  "Irradiator Footprint": "Diện tích chiếm chỗ bộ chiếu xạ",
  "Irradiator Width": "Chiều rộng bộ chiếu xạ",
  "Key Advantage": "Ưu điểm chính",
  "Key Advantage vs FJ100": "Ưu điểm chính so với FJ100",
  "Key Technology": "Công nghệ cốt lõi",
  "LED Lifetime": "Tuổi thọ LED",
  "LED Window Width": "Chiều rộng cửa sổ LED",
  "Lamp Lifetime": "Tuổi thọ đèn",
  "Lamp Power": "Công suất đèn",
  "Lamp Type": "Loại đèn",
  "Length": "Chiều dài",
  "Line Power at 100%": "Công suất đường dây ở 100%",
  "Liquid Light Guide Lengths": "Chiều dài ống dẫn sáng lỏng",
  "Liquid Light Guide Tips": "Đầu ống dẫn sáng lỏng",
  "Max Operating Temperature": "Nhiệt độ hoạt động tối đa",
  "Maximum Dimensions": "Kích thước tối đa",
  "Maximum Fan Capacity": "Công suất quạt tối đa",
  "Maximum Length": "Chiều dài tối đa",
  "Maximum Optical Power": "Công suất quang tối đa",
  "Measurement Accuracy": "Độ chính xác đo lường",
  "Measurement Type": "Loại phép đo",
  "Mercury": "Thủy ngân",
  "Minimum Clearance": "Khoảng hở tối thiểu",
  "Mode Control": "Điều khiển chế độ",
  "Models": "Model",
  "Modularity": "Tính mô-đun",
  "Monitoring Software": "Phần mềm giám sát",
  "Multi-Lamp Control": "Điều khiển đa đèn",
  "Multi-Leg Configurations": "Cấu hình đa nhánh",
  "Multi-Station Use": "Sử dụng đa trạm",
  "NFC": "NFC",
  "Operating Environment": "Môi trường hoạt động",
  "Operating Voltage": "Điện áp hoạt động",
  "Optical Stability": "Độ ổn định quang học",
  "Optics": "Quang học",
  "Outer Dimensions": "Kích thước bên ngoài",
  "Outer Window": "Cửa sổ ngoài",
  "Output Irradiance": "Cường độ bức xạ đầu ra",
  "PLC Interface": "Giao diện PLC",
  "Peak Irradiance": "Cường độ bức xạ đỉnh",
  "Peak Irradiance @ 365 nm": "Cường độ bức xạ đỉnh @ 365 nm",
  "Peak Irradiance @ 385 nm": "Cường độ bức xạ đỉnh @ 385 nm",
  "Peak Irradiance @ 385/395/405 nm": "Cường độ bức xạ đỉnh @ 385/395/405 nm",
  "Peak Irradiance @ 395 nm": "Cường độ bức xạ đỉnh @ 395 nm",
  "Peak Irradiance @ 405 nm": "Cường độ bức xạ đỉnh @ 405 nm",
  "Peak Irradiance at Fiber": "Cường độ bức xạ đỉnh tại cáp quang",
  "Peak Wavelength": "Bước sóng đỉnh",
  "Peak Wavelengths": "Bước sóng đỉnh",
  "Power Cable": "Cáp nguồn",
  "Power Class": "Cấp công suất",
  "Power Classes": "Cấp công suất",
  "Power Consumption": "Mức tiêu thụ điện",
  "Power Factor Correction": "Hiệu chỉnh hệ số công suất",
  "Power Level Options": "Tùy chọn mức công suất",
  "Power Range": "Phạm vi công suất",
  "Power Resolution": "Độ phân giải công suất",
  "Power Supply": "Nguồn điện",
  "Power Supply (Included)": "Nguồn điện (kèm theo)",
  "Primary Application": "Ứng dụng chính",
  "Primary Applications": "Ứng dụng chính",
  "Protection": "Bảo vệ",
  "Quartz Tube Sealing": "Bịt kín ống thạch anh",
  "Radiance at Target": "Độ chói tại mục tiêu",
  "Real-Time Calibration": "Hiệu chuẩn thời gian thực",
  "Reflector Types": "Loại bộ phản xạ",
  "Remote Access": "Truy cập từ xa",
  "Remote Ethernet Functions": "Chức năng Ethernet từ xa",
  "Safety Rating": "Cấp an toàn",
  "Scalability": "Khả năng mở rộng",
  "Sensors": "Cảm biến",
  "Shutter Response Time": "Thời gian phản hồi màn trập",
  "Storage Temp/Humidity": "Nhiệt độ/Độ ẩm lưu trữ",
  "Storage Temperature": "Nhiệt độ lưu trữ",
  "Switching": "Chuyển mạch",
  "Technology": "Công nghệ",
  "Type": "Loại",
  "Typical Dose": "Liều lượng điển hình",
  "Typical UV Emitting Power": "Công suất phát UV điển hình",
  "UV Energy Advantage": "Ưu điểm năng lượng UV",
  "UV LED Head": "Đầu UV LED",
  "UV LED Heads": "Đầu UV LED",
  "UV Power": "Công suất UV",
  "UV Power @ 365 nm (75 mm)": "Công suất UV @ 365 nm (75 mm)",
  "UV Power @ 405 nm / 16 W/cm² (375 mm)": "Công suất UV @ 405 nm / 16 W/cm² (375 mm)",
  "Versions": "Phiên bản",
  "Warranty": "Bảo hành",
  "Water Fittings": "Phụ kiện nước",
  "Wavelength Range": "Phạm vi bước sóng",
  "Wavelengths": "Bước sóng",
  "Weight": "Trọng lượng",
  "Window Dimensions": "Kích thước cửa sổ",
  "Window Lengths": "Chiều dài cửa sổ",
  "Window Width": "Chiều rộng cửa sổ",
  "Working Distance": "Khoảng cách làm việc",
  "vs FE400": "So với FE400",
  "vs Predecessor": "So với phiên bản trước",
};

// Thai translations for product spec-table LABELS (same keys as specLabelZh).
export const specLabelTh: Record<string, string> = {
  "'P' Models": "รุ่น 'P'",
  "48 V Power In (max)": "กำลังไฟเข้า 48 V (สูงสุด)",
  "48 VDC Power In (max)": "กำลังไฟเข้า 48 VDC (สูงสุด)",
  "Accessories": "อุปกรณ์เสริม",
  "Accessory For": "อุปกรณ์เสริมสำหรับ",
  "Adjoining": "การต่อประชิด",
  "Air Ports": "ช่องต่อลม",
  "Ambient Operating Temperature": "อุณหภูมิใช้งานแวดล้อม",
  "Ambient Temp/Humidity": "อุณหภูมิ/ความชื้นแวดล้อม",
  "Amperage / Power (±10%)": "กระแสไฟ / กำลังไฟ (±10%)",
  "Available Lengths": "ความยาวที่มีให้เลือก",
  "Available Wavelengths": "ความยาวคลื่นที่มีให้เลือก",
  "Band-Pass Filters": "ตัวกรองแบนด์พาส",
  "Base Curing Area": "พื้นที่บ่มพื้นฐาน",
  "Base Performance": "ประสิทธิภาพพื้นฐาน",
  "Brand / Series": "แบรนด์ / ซีรีส์",
  "Bulb Fills": "สารบรรจุหลอด",
  "Bulb Length": "ความยาวหลอด",
  "Bulb Type": "ชนิดหลอด",
  "Calibration": "การสอบเทียบ",
  "Calibration Traceability": "ความสามารถสอบกลับการสอบเทียบ",
  "Certifications": "การรับรอง",
  "Cleanroom Ready": "รองรับห้องสะอาด",
  "Communication": "การสื่อสาร",
  "Compatible Controller": "ตัวควบคุมที่รองรับ",
  "Compatible OmniCure Systems": "ระบบ OmniCure ที่รองรับ",
  "Compatible Systems": "ระบบที่รองรับ",
  "Configuration": "การกำหนดค่า",
  "Connector": "ขั้วต่อ",
  "Control": "การควบคุม",
  "Controller": "ตัวควบคุม",
  "Controller Compatibility": "ความเข้ากันได้ของตัวควบคุม",
  "Cooling": "การระบายความร้อน",
  "Cooling Enhancement": "การเพิ่มประสิทธิภาพระบายความร้อน",
  "Cooling Method": "วิธีระบายความร้อน",
  "Cross Section": "หน้าตัด",
  "Cure-Ring Adapter": "อะแดปเตอร์วงแหวนบ่ม",
  "Collimating Adapter": "อะแดปเตอร์รวมลำแสง",
  "Controller Dimensions": "ขนาดตัวควบคุม",
  "Dimensions (L×W×H)": "ขนาด (L×W×H)",
  "Display": "จอแสดงผล",
  "Light-Line Adapter": "อะแดปเตอร์เส้นแสง",
  "Curing Coverage": "พื้นที่ครอบคลุมการบ่ม",
  "Curing Width": "ความกว้างการบ่ม",
  "Curing Width (AC9225/P)": "ความกว้างการบ่ม (AC9225/P)",
  "Curing Widths": "ความกว้างการบ่ม",
  "Custom Sensor Support": "การรองรับเซนเซอร์แบบกำหนดเอง",
  "DC Connector Type": "ชนิดขั้วต่อ DC",
  "Design": "การออกแบบ",
  "Detector": "ตัวตรวจจับ",
  "Emission Length": "ความยาวการเปล่งแสง",
  "Emission Window": "ช่องเปล่งแสง",
  "Emission Window Size": "ขนาดช่องเปล่งแสง",
  "Emitting Widths": "ความกว้างการเปล่งแสง",
  "Emitting Window": "ช่องเปล่งแสง",
  "Energy Savings": "การประหยัดพลังงาน",
  "Ethernet Interface": "อินเทอร์เฟซ Ethernet",
  "Expected LED Lifetime": "อายุการใช้งาน LED ที่คาดหมาย",
  "External Control": "การควบคุมภายนอก",
  "Family": "ตระกูล",
  "Fiber Options": "ตัวเลือกไฟเบอร์",
  "Full AC9 Series Widths": "ความกว้างทั้งหมดของซีรีส์ AC9",
  "Generation": "รุ่นเจเนอเรชัน",
  "Humidity Range": "ช่วงความชื้น",
  "IP Rating": "ระดับการป้องกัน IP",
  "Input Voltage": "แรงดันไฟเข้า",
  "Input Voltages": "แรงดันไฟเข้า",
  "Integration": "การผสานรวม",
  "Intensity Level": "ระดับความเข้ม",
  "Intensity Modes": "โหมดความเข้ม",
  "Irradiance @ 365 nm": "ความเข้มการแผ่รังสี @ 365 nm",
  "Irradiance @ 385 nm": "ความเข้มการแผ่รังสี @ 385 nm",
  "Irradiance @ 395 nm": "ความเข้มการแผ่รังสี @ 395 nm",
  "Irradiance @ 405 nm": "ความเข้มการแผ่รังสี @ 405 nm",
  "Irradiance Range": "ช่วงความเข้มการแผ่รังสี",
  "Irradiance Resolution": "ความละเอียดความเข้มการแผ่รังสี",
  "Irradiator Footprint": "พื้นที่วางตัวฉายรังสี",
  "Irradiator Width": "ความกว้างตัวฉายรังสี",
  "Key Advantage": "ข้อได้เปรียบหลัก",
  "Key Advantage vs FJ100": "ข้อได้เปรียบหลักเทียบกับ FJ100",
  "Key Technology": "เทคโนโลยีหลัก",
  "LED Lifetime": "อายุการใช้งาน LED",
  "LED Window Width": "ความกว้างช่อง LED",
  "Lamp Lifetime": "อายุการใช้งานหลอด",
  "Lamp Power": "กำลังไฟหลอด",
  "Lamp Type": "ชนิดหลอด",
  "Length": "ความยาว",
  "Line Power at 100%": "กำลังไฟสายที่ 100%",
  "Liquid Light Guide Lengths": "ความยาวท่อนำแสงเหลว",
  "Liquid Light Guide Tips": "ปลายท่อนำแสงเหลว",
  "Max Operating Temperature": "อุณหภูมิใช้งานสูงสุด",
  "Maximum Dimensions": "ขนาดสูงสุด",
  "Maximum Fan Capacity": "ความจุพัดลมสูงสุด",
  "Maximum Length": "ความยาวสูงสุด",
  "Maximum Optical Power": "กำลังแสงสูงสุด",
  "Measurement Accuracy": "ความแม่นยำการวัด",
  "Measurement Type": "ชนิดการวัด",
  "Mercury": "ปรอท",
  "Minimum Clearance": "ระยะห่างต่ำสุด",
  "Mode Control": "การควบคุมโหมด",
  "Models": "รุ่น",
  "Modularity": "ความเป็นโมดูลาร์",
  "Monitoring Software": "ซอฟต์แวร์ตรวจสอบ",
  "Multi-Lamp Control": "การควบคุมหลายหลอด",
  "Multi-Leg Configurations": "การกำหนดค่าหลายขา",
  "Multi-Station Use": "การใช้งานหลายสถานี",
  "NFC": "NFC",
  "Operating Environment": "สภาพแวดล้อมการทำงาน",
  "Operating Voltage": "แรงดันไฟใช้งาน",
  "Optical Stability": "เสถียรภาพทางแสง",
  "Optics": "ระบบแสง",
  "Outer Dimensions": "ขนาดภายนอก",
  "Outer Window": "ช่องด้านนอก",
  "Output Irradiance": "ความเข้มการแผ่รังสีขาออก",
  "PLC Interface": "อินเทอร์เฟซ PLC",
  "Peak Irradiance": "ความเข้มการแผ่รังสีสูงสุด",
  "Peak Irradiance @ 365 nm": "ความเข้มการแผ่รังสีสูงสุด @ 365 nm",
  "Peak Irradiance @ 385 nm": "ความเข้มการแผ่รังสีสูงสุด @ 385 nm",
  "Peak Irradiance @ 385/395/405 nm": "ความเข้มการแผ่รังสีสูงสุด @ 385/395/405 nm",
  "Peak Irradiance @ 395 nm": "ความเข้มการแผ่รังสีสูงสุด @ 395 nm",
  "Peak Irradiance @ 405 nm": "ความเข้มการแผ่รังสีสูงสุด @ 405 nm",
  "Peak Irradiance at Fiber": "ความเข้มการแผ่รังสีสูงสุดที่ไฟเบอร์",
  "Peak Wavelength": "ความยาวคลื่นสูงสุด",
  "Peak Wavelengths": "ความยาวคลื่นสูงสุด",
  "Power Cable": "สายไฟ",
  "Power Class": "ระดับกำลังไฟ",
  "Power Classes": "ระดับกำลังไฟ",
  "Power Consumption": "การใช้พลังงาน",
  "Power Factor Correction": "การแก้ตัวประกอบกำลัง",
  "Power Level Options": "ตัวเลือกระดับกำลังไฟ",
  "Power Range": "ช่วงกำลังไฟ",
  "Power Resolution": "ความละเอียดกำลังไฟ",
  "Power Supply": "แหล่งจ่ายไฟ",
  "Power Supply (Included)": "แหล่งจ่ายไฟ (รวมมาให้)",
  "Primary Application": "การใช้งานหลัก",
  "Primary Applications": "การใช้งานหลัก",
  "Protection": "การป้องกัน",
  "Quartz Tube Sealing": "การปิดผนึกท่อควอตซ์",
  "Radiance at Target": "ความสว่างที่เป้าหมาย",
  "Real-Time Calibration": "การสอบเทียบแบบเรียลไทม์",
  "Reflector Types": "ชนิดตัวสะท้อนแสง",
  "Remote Access": "การเข้าถึงระยะไกล",
  "Remote Ethernet Functions": "ฟังก์ชัน Ethernet ระยะไกล",
  "Safety Rating": "ระดับความปลอดภัย",
  "Scalability": "ความสามารถในการขยาย",
  "Sensors": "เซนเซอร์",
  "Shutter Response Time": "เวลาตอบสนองชัตเตอร์",
  "Storage Temp/Humidity": "อุณหภูมิ/ความชื้นการจัดเก็บ",
  "Storage Temperature": "อุณหภูมิการจัดเก็บ",
  "Switching": "การสลับ",
  "Technology": "เทคโนโลยี",
  "Type": "ชนิด",
  "Typical Dose": "ปริมาณโดยทั่วไป",
  "Typical UV Emitting Power": "กำลังเปล่ง UV โดยทั่วไป",
  "UV Energy Advantage": "ข้อได้เปรียบพลังงาน UV",
  "UV LED Head": "หัว UV LED",
  "UV LED Heads": "หัว UV LED",
  "UV Power": "กำลังไฟ UV",
  "UV Power @ 365 nm (75 mm)": "กำลังไฟ UV @ 365 nm (75 mm)",
  "UV Power @ 405 nm / 16 W/cm² (375 mm)": "กำลังไฟ UV @ 405 nm / 16 W/cm² (375 mm)",
  "Versions": "เวอร์ชัน",
  "Warranty": "การรับประกัน",
  "Water Fittings": "ข้อต่อน้ำ",
  "Wavelength Range": "ช่วงความยาวคลื่น",
  "Wavelengths": "ความยาวคลื่น",
  "Weight": "น้ำหนัก",
  "Window Dimensions": "ขนาดช่อง",
  "Window Lengths": "ความยาวช่อง",
  "Window Width": "ความกว้างช่อง",
  "Working Distance": "ระยะทำงาน",
  "vs FE400": "เทียบกับ FE400",
  "vs Predecessor": "เทียบกับรุ่นก่อนหน้า",
};

// Localized spec label; falls back to the English source for any locale/label
// without a translation.
export function localizeSpecLabel(label: string, locale: "en" | "zh" | "vi" | "th"): string {
  if (locale === "zh") return specLabelZh[label] ?? label;
  if (locale === "vi") return specLabelVi[label] ?? label;
  if (locale === "th") return specLabelTh[label] ?? label;
  return label;
}
