// Chinese translations for product spec-table LABELS (the left column only).
// Spec values stay language-neutral (numbers, units, model names). Any label
// not present here falls back to its English source.
export const specLabelZh: Record<string, string> = {
  "'P' Models": "「P」型号",
  "48 V Power In (max)": "48V 输入功率（最大）",
  "48 VDC Power In (max)": "48VDC 输入功率（最大）",
  "Accessories": "配件",
  "Accessory For": "适配于",
  "Adjoining": "拼接",
  "Air Ports": "气路接口",
  "Ambient Operating Temperature": "环境工作温度",
  "Ambient Temp/Humidity": "环境温度/湿度",
  "Amperage / Power (±10%)": "电流 / 功率（±10%）",
  "Available Lengths": "可选长度",
  "Available Wavelengths": "可选波长",
  "Band-Pass Filters": "带通滤光片",
  "Base Curing Area": "基础固化面积",
  "Base Performance": "基础性能",
  "Brand / Series": "品牌 / 系列",
  "Bulb Fills": "灯泡填充物",
  "Bulb Length": "灯泡长度",
  "Bulb Type": "灯泡类型",
  "Calibration": "校准",
  "Calibration Traceability": "校准溯源",
  "Certifications": "认证",
  "Cleanroom Ready": "洁净室适用",
  "Communication": "通信",
  "Compatible Controller": "兼容控制器",
  "Compatible OmniCure Systems": "兼容 OmniCure 系统",
  "Compatible Systems": "兼容系统",
  "Configuration": "配置",
  "Connector": "连接器",
  "Control": "控制",
  "Controller": "控制器",
  "Controller Compatibility": "控制器兼容性",
  "Cooling": "冷却",
  "Cooling Enhancement": "冷却增强",
  "Cooling Method": "冷却方式",
  "Cross Section": "截面尺寸",
  "Cure-Ring Adapter": "固化环适配器",
  "Collimating Adapter": "准直适配器",
  "Controller Dimensions": "控制器尺寸",
  "Dimensions (L×W×H)": "尺寸（长×宽×高）",
  "Display": "显示屏",
  "Light-Line Adapter": "线光适配器",
  "Curing Coverage": "固化覆盖",
  "Curing Width": "固化宽度",
  "Curing Width (AC9225/P)": "固化宽度（AC9225/P）",
  "Curing Widths": "固化宽度",
  "Custom Sensor Support": "定制传感器支持",
  "DC Connector Type": "直流连接器类型",
  "Design": "设计",
  "Detector": "探测器",
  "Emission Length": "发光长度",
  "Emission Window": "发光窗口",
  "Emission Window Size": "发光窗口尺寸",
  "Emitting Widths": "发光宽度",
  "Emitting Window": "发光窗口",
  "Energy Savings": "节能",
  "Ethernet Interface": "以太网接口",
  "Expected LED Lifetime": "预期 LED 寿命",
  "External Control": "外部控制",
  "Family": "系列",
  "Fiber Options": "光纤选项",
  "Full AC9 Series Widths": "AC9 系列全部宽度",
  "Generation": "代次",
  "Humidity Range": "湿度范围",
  "IP Rating": "IP 防护等级",
  "Input Voltage": "输入电压",
  "Input Voltages": "输入电压",
  "Integration": "集成",
  "Intensity Level": "强度等级",
  "Intensity Modes": "强度模式",
  "Irradiance @ 365 nm": "辐照度 @ 365 nm",
  "Irradiance @ 385 nm": "辐照度 @ 385 nm",
  "Irradiance @ 395 nm": "辐照度 @ 395 nm",
  "Irradiance @ 405 nm": "辐照度 @ 405 nm",
  "Irradiance Range": "辐照度范围",
  "Irradiance Resolution": "辐照度分辨率",
  "Irradiator Footprint": "辐照器占位尺寸",
  "Irradiator Width": "辐照器宽度",
  "Key Advantage": "主要优势",
  "Key Advantage vs FJ100": "相较 FJ100 的主要优势",
  "Key Technology": "核心技术",
  "LED Lifetime": "LED 寿命",
  "LED Window Width": "LED 窗口宽度",
  "Lamp Lifetime": "灯泡寿命",
  "Lamp Power": "灯泡功率",
  "Lamp Type": "灯泡类型",
  "Length": "长度",
  "Line Power at 100%": "100% 时线路功率",
  "Liquid Light Guide Lengths": "液体导光管长度",
  "Liquid Light Guide Tips": "液体导光管端头",
  "Max Operating Temperature": "最高工作温度",
  "Maximum Dimensions": "最大尺寸",
  "Maximum Fan Capacity": "最大风扇风量",
  "Maximum Length": "最大长度",
  "Maximum Optical Power": "最大光功率",
  "Measurement Accuracy": "测量精度",
  "Measurement Type": "测量类型",
  "Mercury": "汞",
  "Minimum Clearance": "最小间隙",
  "Mode Control": "模式控制",
  "Models": "型号",
  "Modularity": "模块化",
  "Monitoring Software": "监控软件",
  "Multi-Lamp Control": "多灯控制",
  "Multi-Leg Configurations": "多腿配置",
  "Multi-Station Use": "多工位使用",
  "NFC": "NFC",
  "Operating Environment": "工作环境",
  "Operating Voltage": "工作电压",
  "Optical Stability": "光学稳定性",
  "Optics": "光学",
  "Outer Dimensions": "外形尺寸",
  "Outer Window": "外窗口",
  "Output Irradiance": "输出辐照度",
  "PLC Interface": "PLC 接口",
  "Peak Irradiance": "峰值辐照度",
  "Peak Irradiance @ 365 nm": "峰值辐照度 @ 365 nm",
  "Peak Irradiance @ 385 nm": "峰值辐照度 @ 385 nm",
  "Peak Irradiance @ 385/395/405 nm": "峰值辐照度 @ 385/395/405 nm",
  "Peak Irradiance @ 395 nm": "峰值辐照度 @ 395 nm",
  "Peak Irradiance @ 405 nm": "峰值辐照度 @ 405 nm",
  "Peak Irradiance at Fiber": "光纤处峰值辐照度",
  "Peak Wavelength": "峰值波长",
  "Peak Wavelengths": "峰值波长",
  "Power Cable": "电源线缆",
  "Power Class": "功率等级",
  "Power Classes": "功率等级",
  "Power Consumption": "功耗",
  "Power Factor Correction": "功率因数校正",
  "Power Level Options": "功率档位选项",
  "Power Range": "功率范围",
  "Power Resolution": "功率分辨率",
  "Power Supply": "电源",
  "Power Supply (Included)": "电源（含）",
  "Primary Application": "主要应用",
  "Primary Applications": "主要应用",
  "Protection": "防护",
  "Quartz Tube Sealing": "石英管密封",
  "Radiance at Target": "目标处辐射度",
  "Real-Time Calibration": "实时校准",
  "Reflector Types": "反射器类型",
  "Remote Access": "远程访问",
  "Remote Ethernet Functions": "远程以太网功能",
  "Safety Rating": "安全等级",
  "Scalability": "可扩展性",
  "Sensors": "传感器",
  "Shutter Response Time": "快门响应时间",
  "Storage Temp/Humidity": "存储温度/湿度",
  "Storage Temperature": "存储温度",
  "Switching": "开关切换",
  "Technology": "技术",
  "Type": "类型",
  "Typical Dose": "典型剂量",
  "Typical UV Emitting Power": "典型 UV 发射功率",
  "UV Energy Advantage": "UV 能量优势",
  "UV LED Head": "UV LED 灯头",
  "UV LED Heads": "UV LED 灯头",
  "UV Power": "UV 功率",
  "UV Power @ 365 nm (75 mm)": "UV 功率 @ 365 nm（75 mm）",
  "UV Power @ 405 nm / 16 W/cm² (375 mm)": "UV 功率 @ 405 nm / 16 W/cm²（375 mm）",
  "Versions": "版本",
  "Warranty": "保修",
  "Water Fittings": "水路接口",
  "Wavelength Range": "波长范围",
  "Wavelengths": "波长",
  "Weight": "重量",
  "Window Dimensions": "窗口尺寸",
  "Window Lengths": "窗口长度",
  "Window Width": "窗口宽度",
  "Working Distance": "工作距离",
  "vs FE400": "相较 FE400",
  "vs Predecessor": "相较前代",
};

// Localized spec label; falls back to the English source for any locale/label
// without a translation.
export function localizeSpecLabel(label: string, locale: "en" | "zh" | "vi" | "th"): string {
  if (locale === "zh") return specLabelZh[label] ?? label;
  return label;
}
